souffle: parser/ParserDriver.cpp File Reference
ParserDriver.cpp File Reference
#include "parser/ParserDriver.h"
#include "Global.h"
#include "ast/Clause.h"
#include "ast/Component.h"
#include "ast/ComponentInit.h"
#include "ast/FunctorDeclaration.h"
#include "ast/IO.h"
#include "ast/Pragma.h"
#include "ast/Program.h"
#include "ast/QualifiedName.h"
#include "ast/Relation.h"
#include "ast/SubsetType.h"
#include "ast/TranslationUnit.h"
#include "ast/Type.h"
#include "ast/Utils.h"
#include "reports/ErrorReport.h"
#include "souffle/utility/ContainerUtil.h"
#include "souffle/utility/FunctionalUtil.h"
#include "souffle/utility/StreamUtil.h"
#include "souffle/utility/StringUtil.h"
#include "souffle/utility/tinyformat.h"
#include <algorithm>
#include <memory>
#include <utility>
#include <vector>
Namespaces
souffle
Souffle - A Datalog Compiler Copyright (c) 2013, 2015, Oracle and/or its affiliates.
Typedefs
using YY_BUFFER_STATE = struct yy_buffer_state *
Functions
YY_BUFFER_STATE yy_scan_string (const char *, yyscan_t scanner)
int yylex_destroy (yyscan_t scanner)
int yylex_init_extra (scanner_data *data, yyscan_t *scanner)
void yyset_in (FILE *in_str, yyscan_t scanner)
Typedef Documentation
YY_BUFFER_STATE
using YY_BUFFER_STATE = struct yy_buffer_state*
Definition at line 43 of file ParserDriver.cpp.
Function Documentation
yy_scan_string()
YY_BUFFER_STATE yy_scan_string (const char * , yyscan_t scanner)
Referenced by souffle::ParserDriver::parse().
yylex_destroy()
int yylex_destroy (yyscan_t scanner)
Referenced by souffle::ParserDriver::parse().
yylex_init_extra()
int yylex_init_extra (scanner_data * data, yyscan_t * scanner)
Referenced by souffle::ParserDriver::parse().
yyset_in()
void yyset_in (FILE * in_str, yyscan_t scanner)
Referenced by souffle::ParserDriver::parse().