souffle: souffle::NormalisedClause Class Reference
souffle::NormalisedClause Class Reference
#include <ClauseNormalisation.h>
Data Structures
struct NormalisedClauseElement
Public Member Functions
const std::set< std::string > & getConstants () const
const std::vector< NormalisedClauseElement > & getElements () const
const std::set< std::string > & getVariables () const
bool isFullyNormalised () const
NormalisedClause ()=default
NormalisedClause (const AstClause *clause)
Private Member Functions
void addClauseAtom (const std::string &qualifier, const std::string &scopeID, const AstAtom *atom)
Parse an atom with a preset name qualifier into the element list.
void addClauseBodyLiteral (const std::string &scopeID, const AstLiteral *lit)
Parse a body literal into the element list.
std::string normaliseArgument (const AstArgument *arg)
Return a normalised string repr of an argument.
Private Attributes
size_t aggrScopeCount {0}
std::vector< NormalisedClauseElement > clauseElements {}
std::set< std::string > constants {}
bool fullyNormalised {true}
std::set< std::string > variables {}
Detailed Description
Definition at line 35 of file ClauseNormalisation.h.
Constructor & Destructor Documentation
NormalisedClause() [1/2]
souffle::NormalisedClause::NormalisedClause () default
Referenced by souffle::ClauseNormalisationAnalysis::run().
NormalisedClause() [2/2]
souffle::NormalisedClause::NormalisedClause (const AstClause * clause)
Definition at line 36 of file ClauseNormalisation.cpp.
References addClauseBodyLiteral(), clauseElements, souffle::AstAtom::getArguments(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), and normaliseArgument().
{
     // head
     AstQualifiedName name("@min:head");
     std::vector<std::string> headVars;
     for (const auto* arg : clause->getHead()->getArguments()) {
         headVars.push_back(normaliseArgument(arg));
     }
     clauseElements.push_back({.name = name, .params = headVars});
     // body
     for (const auto* lit : clause->getBodyLiterals()) {
         addClauseBodyLiteral("@min:scope:0", lit);
     }
 }
Member Function Documentation
addClauseAtom()
void souffle::NormalisedClause::addClauseAtom (const std::string & qualifier, const std::string & scopeID, const AstAtom * atom) private
Parse an atom with a preset name qualifier into the element list.
Definition at line 51 of file ClauseNormalisation.cpp.
References clauseElements, souffle::AstAtom::getArguments(), souffle::AstAtom::getQualifiedName(), normaliseArgument(), and souffle::AstQualifiedName::prepend().
Referenced by addClauseBodyLiteral().
{
     AstQualifiedName name(atom->getQualifiedName());
     name.prepend(qualifier);
     std::vector<std::string> vars;
     vars.push_back(scopeID);
     for (const auto* arg : atom->getArguments()) {
         vars.push_back(normaliseArgument(arg));
     }
     clauseElements.push_back({.name = name, .params = vars});
 }
addClauseBodyLiteral()
void souffle::NormalisedClause::addClauseBodyLiteral (const std::string & scopeID, const AstLiteral * lit) private
Parse a body literal into the element list.
Definition at line 64 of file ClauseNormalisation.cpp.
References addClauseAtom(), clauseElements, fullyNormalised, normaliseArgument(), souffle::AstQualifiedName::prepend(), souffle::toBinaryConstraintSymbol(), and souffle::toString().
Referenced by normaliseArgument(), and NormalisedClause().
{
     if (const auto* atom = dynamic_cast<const AstAtom*>(lit)) {
         addClauseAtom("@min:atom", scopeID, atom);
     } else if (const auto* neg = dynamic_cast<const AstNegation*>(lit)) {
         addClauseAtom("@min:neg", scopeID, neg->getAtom());
     } else if (const auto* bc = dynamic_cast<const AstBinaryConstraint*>(lit)) {
         AstQualifiedName name(toBinaryConstraintSymbol(bc->getOperator()));
         name.prepend("@min:operator");
         std::vector<std::string> vars;
         vars.push_back(scopeID);
         vars.push_back(normaliseArgument(bc->getLHS()));
         vars.push_back(normaliseArgument(bc->getRHS()));
         clauseElements.push_back({.name = name, .params = vars});
     } else {
         assert(lit != nullptr && "unexpected nullptr lit");
         fullyNormalised = false;
         std::stringstream qualifier;
         qualifier << "@min:unhandled:lit:" << scopeID;
         AstQualifiedName name(toString(*lit));
         name.prepend(qualifier.str());
         clauseElements.push_back({.name = name, .params = std::vector<std::string>()});
     }
 }
getConstants()
const std::set<std::string>& souffle::NormalisedClause::getConstants () const inline
Definition at line 54 of file ClauseNormalisation.h.
References constants.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return constants;
     }
getElements()
const std::vector<NormalisedClauseElement>& souffle::NormalisedClause::getElements () const inline
Definition at line 58 of file ClauseNormalisation.h.
References clauseElements.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return clauseElements;
     }
getVariables()
const std::set<std::string>& souffle::NormalisedClause::getVariables () const inline
Definition at line 50 of file ClauseNormalisation.h.
References variables.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return variables;
     }
isFullyNormalised()
bool souffle::NormalisedClause::isFullyNormalised () const inline
Definition at line 46 of file ClauseNormalisation.h.
References fullyNormalised.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent().
{
         return fullyNormalised;
     }
normaliseArgument()
std::string souffle::NormalisedClause::normaliseArgument (const AstArgument * arg) private
Return a normalised string repr of an argument.
Definition at line 88 of file ClauseNormalisation.cpp.
References addClauseBodyLiteral(), aggrScopeCount, clauseElements, constants, fullyNormalised, and variables.
Referenced by addClauseAtom(), addClauseBodyLiteral(), and NormalisedClause().
{
     if (auto* stringCst = dynamic_cast<const AstStringConstant*>(arg)) {
         std::stringstream name;
         name << "@min:cst:str" << *stringCst;
         constants.insert(name.str());
         return name.str();
     } else if (auto* numericCst = dynamic_cast<const AstNumericConstant*>(arg)) {
         std::stringstream name;
         name << "@min:cst:num:" << *numericCst;
         constants.insert(name.str());
         return name.str();
     } else if (dynamic_cast<const AstNilConstant*>(arg) != nullptr) {
         constants.insert("@min:cst:nil");
         return "@min:cst:nil";
     } else if (auto* var = dynamic_cast<const AstVariable*>(arg)) {
         auto name = var->getName();
         variables.insert(name);
         return name;
     } else if (dynamic_cast<const AstUnnamedVariable*>(arg)) {
         static size_t countUnnamed = 0;
         std::stringstream name;
         name << "@min:unnamed:" << countUnnamed++;
         variables.insert(name.str());
         return name.str();
     } else if (auto* aggr = dynamic_cast<const AstAggregator*>(arg)) {
         // Set the scope to uniquely identify the aggregator
         std::stringstream scopeID;
         scopeID << "@min:scope:" << ++aggrScopeCount;
         variables.insert(scopeID.str());
         // Set the type signature of this aggregator
         std::stringstream aggrTypeSignature;
         aggrTypeSignature << "@min:aggrtype";
         std::vector<std::string> aggrTypeSignatureComponents;
         // - the operator is fixed and cannot be changed
         aggrTypeSignature << ":" << aggr->getOperator();
         // - the scope can be remapped as a variable
         aggrTypeSignatureComponents.push_back(scopeID.str());
         // - the normalised target expression can be remapped as a variable
         if (aggr->getTargetExpression() != nullptr) {
             std::string normalisedExpr = normaliseArgument(aggr->getTargetExpression());
             aggrTypeSignatureComponents.push_back(normalisedExpr);
         }
         // Type signature is its own special atom
         clauseElements.push_back({.name = aggrTypeSignature.str(), .params = aggrTypeSignatureComponents});
         // Add each contained normalised clause literal, tying it with the new scope ID
         for (const auto* literal : aggr->getBodyLiterals()) {
             addClauseBodyLiteral(scopeID.str(), literal);
         }
         // Aggregator identified by the scope ID
         return scopeID.str();
     } else {
         fullyNormalised = false;
         return "@min:unhandled:arg";
     }
 }
Field Documentation
aggrScopeCount
size_t souffle::NormalisedClause::aggrScopeCount {0} private
Definition at line 64 of file ClauseNormalisation.h.
Referenced by normaliseArgument().
clauseElements
std::vector<NormalisedClauseElement> souffle::NormalisedClause::clauseElements {} private
Definition at line 67 of file ClauseNormalisation.h.
Referenced by addClauseAtom(), addClauseBodyLiteral(), getElements(), normaliseArgument(), and NormalisedClause().
constants
std::set<std::string> souffle::NormalisedClause::constants {} private
Definition at line 66 of file ClauseNormalisation.h.
Referenced by getConstants(), and normaliseArgument().
fullyNormalised
bool souffle::NormalisedClause::fullyNormalised {true} private
Definition at line 63 of file ClauseNormalisation.h.
Referenced by addClauseBodyLiteral(), isFullyNormalised(), and normaliseArgument().
variables
std::set<std::string> souffle::NormalisedClause::variables {} private
Definition at line 65 of file ClauseNormalisation.h.
Referenced by getVariables(), and normaliseArgument().
The documentation for this class was generated from the following files:
ast/analysis/ClauseNormalisation.h
ast/analysis/ClauseNormalisation.cpp