souffle: souffle::GroundedTermsChecker Class Reference
souffle::GroundedTermsChecker Class Reference
#include <GroundedTermsChecker.h>
Public Member Functions
GroundedTermsChecker * clone () const override
std::string getName () const override
void verify (AstTranslationUnit &translationUnit)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Definition at line 26 of file GroundedTermsChecker.h.
Member Function Documentation
clone()
GroundedTermsChecker* souffle::GroundedTermsChecker::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 35 of file GroundedTermsChecker.h.
{
         return new GroundedTermsChecker();
     }
getName()
std::string souffle::GroundedTermsChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 28 of file GroundedTermsChecker.h.
References verify().
{
         return "GroundedTermsChecker";
     }
transform()
bool souffle::GroundedTermsChecker::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 40 of file GroundedTermsChecker.h.
References verify().
{
         verify(translationUnit);
         return false;
     }
verify()
void souffle::GroundedTermsChecker::verify (AstTranslationUnit & translationUnit)
Definition at line 34 of file GroundedTermsChecker.cpp.
References souffle::AstTranslationUnit::getErrorReport(), souffle::getGroundedTerms(), souffle::AstTranslationUnit::getProgram(), souffle::getVariables(), souffle::isFact(), and souffle::visitDepthFirst().
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), getName(), and transform().
{
     auto&& program = *translationUnit.getProgram();
     auto&& report = translationUnit.getErrorReport();
     // -- check grounded variables and records --
     visitDepthFirst(program.getClauses(), [&](const AstClause& clause) {
         if (isFact(clause)) return;  // only interested in rules
         auto isGrounded = getGroundedTerms(translationUnit, clause);
         std::set<std::string> reportedVars;
         // all terms in head need to be grounded
         for (auto&& cur : getVariables(clause)) {
             if (!isGrounded[cur] && reportedVars.insert(cur->getName()).second) {
                 report.addError("Ungrounded variable " + cur->getName(), cur->getSrcLoc());
             }
         }
         // all records need to be grounded
         visitDepthFirst(clause, [&](const AstRecordInit& record) {
             if (!isGrounded[&record]) {
                 report.addError("Ungrounded record", record.getSrcLoc());
             }
         });
         // All sums need to be grounded
         visitDepthFirst(clause, [&](const AstBranchInit& adt) {
             if (!isGrounded[&adt]) {
                 report.addError("Ungrounded ADT branch", adt.getSrcLoc());
             }
         });
     });
 }
The documentation for this class was generated from the following files:
ast/transform/GroundedTermsChecker.h
ast/transform/GroundedTermsChecker.cpp