souffle: souffle::ADTtoRecordsTransformer Class Reference
souffle::ADTtoRecordsTransformer Class Reference
#include <ADTtoRecords.h>
Public Member Functions
ADTtoRecordsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Definition at line 26 of file ADTtoRecords.h.
Member Function Documentation
clone()
ADTtoRecordsTransformer* souffle::ADTtoRecordsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 32 of file ADTtoRecords.h.
References transform().
{
         return new ADTtoRecordsTransformer();
     }
getName()
std::string souffle::ADTtoRecordsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 28 of file ADTtoRecords.h.
{
         return "ADTtoRecords";
     }
transform()
bool souffle::ADTtoRecordsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 31 of file ADTtoRecords.cpp.
References souffle::AstProgram::apply(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), and souffle::SumTypeBranchesAnalysis::unsafeGetType().
Referenced by clone().
{
     struct ADTsFuneral : public AstNodeMapper {
         mutable bool changed{false};
         AstTranslationUnit& tu;
         const SumTypeBranchesAnalysis& sumTypesBranches = *tu.getAnalysis<SumTypeBranchesAnalysis>();
         ADTsFuneral(AstTranslationUnit& tu) : tu(tu){};
         Own<AstNode> operator()(Own<AstNode> node) const override {
             // Rewrite sub-expressions first
             node->apply(*this);
             if (!isA<AstBranchInit>(node)) {
                 return node;
             }
             changed = true;
             auto& adt = *as<AstBranchInit>(node);
             auto& type = sumTypesBranches.unsafeGetType(adt.getConstructor());
             assert(isA<AlgebraicDataType>(type));
             auto& branches = as<AlgebraicDataType>(type)->getBranches();
             // Find branch ID.
             AlgebraicDataType::Branch searchDummy{adt.getConstructor(), {}};
             auto iterToBranch = std::lower_bound(branches.begin(), branches.end(), searchDummy,
                     [](const AlgebraicDataType::Branch& left, const AlgebraicDataType::Branch& right) {
                         return left.name < right.name;
                     });
             // Branch id corresponds to the position in lexicographical ordering.
             auto branchID = std::distance(std::begin(branches), iterToBranch);
             // Collect branch arguments
             VecOwn<AstArgument> branchArguments;
             for (auto* arg : adt.getArguments()) {
                 branchArguments.emplace_back(arg->clone());
             }
             // Store branch arguments as record [branch_args...]
             auto branchArgsAsRecord = mk<AstArgument, AstRecordInit>(std::move(branchArguments));
             // Arguments for the resulting record [branch_id, [branch_args...]].
             VecOwn<AstArgument> finalRecordArgs;
             finalRecordArgs.push_back(mk<AstArgument, AstNumericConstant>(branchID));
             finalRecordArgs.push_back(std::move(branchArgsAsRecord));
             return mk<AstRecordInit>(std::move(finalRecordArgs), adt.getSrcLoc());
         }
     };
     ADTsFuneral mapper(tu);
     tu.getProgram()->apply(mapper);
     return mapper.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ADTtoRecords.h
ast/transform/ADTtoRecords.cpp