souffle: souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer Class Reference
souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer Class Reference
Runs the first stage of the labelling algorithm.
#include <MagicSet.h>
Public Member Functions
NegativeLabellingTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static AstQualifiedName getNegativeLabel (const AstQualifiedName &name)
Provide a unique name for negatively-labelled relations.
Detailed Description
Runs the first stage of the labelling algorithm.
Separates out negated appearances of relations from the main SCC graph, preventing them from affecting stratification once magic dependencies are added.
Definition at line 171 of file MagicSet.h.
Member Function Documentation
clone()
NegativeLabellingTransformer* souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 177 of file MagicSet.h.
References souffle::MagicSetTransformer::transform().
{
         return new NegativeLabellingTransformer();
     }
getName()
std::string souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 173 of file MagicSet.h.
{
         return "NegativeLabellingTransformer";
     }
getNegativeLabel()
AstQualifiedName souffle::NegativeLabellingTransformer::getNegativeLabel (const AstQualifiedName & name) static private
Provide a unique name for negatively-labelled relations.
Definition at line 647 of file MagicSet.cpp.
References souffle::AstQualifiedName::prepend().
{
     AstQualifiedName newName(name);
     newName.prepend("@neglabel");
     return newName;
 }
transform()
bool souffle::NegativeLabellingTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 667 of file MagicSet.cpp.
References souffle::clone(), souffle::contains(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstNegation::getAtom(), souffle::getClauses(), souffle::MagicSetTransformer::getIgnoredRelations(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::renameAtoms(), and souffle::visitDepthFirst().
{
     const auto& sccGraph = *translationUnit.getAnalysis<SCCGraphAnalysis>();
     auto& program = *translationUnit.getProgram();
     std::set<AstQualifiedName> relationsToLabel;
     std::set<std::unique_ptr<AstClause>> clausesToAdd;
     auto ignoredRelations = getIgnoredRelations(translationUnit);
     // Negatively label all relations that might affect stratification after MST
     //      - Negated relations
     //      - Relations that appear in aggregators
     visitDepthFirst(program, [&](const AstNegation& neg) {
         auto* atom = neg.getAtom();
         auto relName = atom->getQualifiedName();
         if (contains(ignoredRelations, relName)) return;
         atom->setQualifiedName(getNegativeLabel(relName));
         relationsToLabel.insert(relName);
     });
     visitDepthFirst(program, [&](const AstAggregator& aggr) {
         visitDepthFirst(aggr, [&](const AstAtom& atom) {
             auto relName = atom.getQualifiedName();
             if (contains(ignoredRelations, relName)) return;
             const_cast<AstAtom&>(atom).setQualifiedName(getNegativeLabel(relName));
             relationsToLabel.insert(relName);
         });
     });
     // Copy over the rules for labelled relations one stratum at a time
     for (size_t stratum = 0; stratum < sccGraph.getNumberOfSCCs(); stratum++) {
         // Check which relations to label in this stratum
         const auto& stratumRels = sccGraph.getInternalRelations(stratum);
         std::map<AstQualifiedName, AstQualifiedName> newSccFriendNames;
         for (const auto* rel : stratumRels) {
             auto relName = rel->getQualifiedName();
             if (contains(ignoredRelations, relName)) continue;
             relationsToLabel.insert(relName);
             newSccFriendNames[relName] = getNegativeLabel(relName);
         }
         // Negatively label the relations in a new copy of this stratum
         for (const auto* rel : stratumRels) {
             for (auto* clause : getClauses(program, rel->getQualifiedName())) {
                 auto neggedClause = souffle::clone(clause);
                 renameAtoms(*neggedClause, newSccFriendNames);
                 clausesToAdd.insert(std::move(neggedClause));
             }
         }
     }
     // Add in all the relations that were labelled
     for (const auto& relName : relationsToLabel) {
         const auto* originalRel = getRelation(program, relName);
         assert(originalRel != nullptr && "unlabelled relation does not exist");
         auto labelledRelation = souffle::clone(originalRel);
         labelledRelation->setQualifiedName(getNegativeLabel(relName));
         program.addRelation(std::move(labelledRelation));
     }
     // Add in all the negged clauses
     for (const auto& clause : clausesToAdd) {
         program.addClause(souffle::clone(clause));
     }
     return !relationsToLabel.empty();
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp