souffle: souffle::MakeIndexTransformer Class Reference
souffle::MakeIndexTransformer Class Reference
Make indexable operations to indexed operations.
#include <MakeIndex.h>
Public Types
using ExpressionPair = std::pair< std::unique_ptr< RamExpression >, std::unique_ptr< RamExpression > >
Get expression of RAM element access.
Public Member Functions
std::unique_ptr< RamCondition > constructPattern (const std::vector< std::string > &attributeTypes, RamPattern &queryPattern, bool &indexable, std::vector< std::unique_ptr< RamCondition >> conditionList, int identifier)
ExpressionPair getFloatExpressionPair (const RamConstraint *binRelOp, size_t &element, int identifier)
ExpressionPair getLowerUpperExpression (RamCondition *c, size_t &element, int level)
std::string getName () const override
get name of the transformer
ExpressionPair getSignedExpressionPair (const RamConstraint *binRelOp, size_t &element, int identifier)
ExpressionPair getUnsignedExpressionPair (const RamConstraint *binRelOp, size_t &element, int identifier)
bool makeIndex (RamProgram &program)
Make indexable RAM operation indexed.
std::unique_ptr< RamOperation > rewriteAggregate (const RamAggregate *agg)
Rewrite an aggregate operation to an indexed aggregate operation.
std::unique_ptr< RamOperation > rewriteIndexScan (const RamIndexScan *iscan)
Rewrite an index scan operation to an amended index scan operation.
std::unique_ptr< RamOperation > rewriteScan (const RamScan *scan)
Rewrite a scan operation to an indexed scan operation.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamLevelAnalysis * rla {nullptr}
Detailed Description
Make indexable operations to indexed operations.
The transformer assumes that the RAM has been levelled before. The conditions that could be used for an index must be located immediately after the scan or aggregate operation.
QUERY
 ...
 FOR t1 IN A
  IF t1.x = 10 /\ t1.y = 20 /\ C
   ...
will be rewritten to
QUERY
 ...
  SEARCH t1 IN A INDEX t1.x=10 AND t1.y = 20
   IF C
    ...
Definition at line 64 of file MakeIndex.h.
Member Typedef Documentation
ExpressionPair
using souffle::MakeIndexTransformer::ExpressionPair = std::pair<std::unique_ptr<RamExpression>, std::unique_ptr<RamExpression> >
Get expression of RAM element access.
Parameters
Equivalence constraints of the format t1.x = <expression> or <expression> = t1.x
Element that was accessed, e.g., for t1.x this would be the index of attribute x.
Tuple identifier
The method retrieves expression the expression of an equivalence constraint of the format t1.x = <expr> or <expr> = t1.x
Definition at line 80 of file MakeIndex.h.
Member Function Documentation
constructPattern()
std::unique_ptr< RamCondition > souffle::MakeIndexTransformer::constructPattern (const std::vector< std::string > & attributeTypes, RamPattern & queryPattern, bool & indexable, std::vector< std::unique_ptr< RamCondition >> conditionList, int identifier)
Parameters
AttributeTypes to indicate type of each attribute in the relation
Query pattern that is to be constructed
Flag to indicate whether operation is indexable
A list of conditions that will be transformed to query patterns
Tuple identifier of the indexable operation
Returns
Remaining conditions that could not be transformed to an index
Definition at line 265 of file MakeIndex.cpp.
References souffle::clone(), souffle::getEqConstraint(), souffle::getGreaterEqualConstraint(), souffle::getLessEqualConstraint(), getLowerUpperExpression(), souffle::getMaxOp(), souffle::getMinOp(), souffle::identifier(), and souffle::isRamUndefValue().
Referenced by rewriteAggregate(), rewriteIndexScan(), and rewriteScan().
{
     // Remaining conditions which cannot be handled by an index
     std::unique_ptr<RamCondition> condition;
     auto addCondition = [&](std::unique_ptr<RamCondition> c) {
         if (condition != nullptr) {
             condition = std::make_unique<RamConjunction>(std::move(condition), std::move(c));
         } else {
             condition = std::move(c);
         }
     };
     // Build query pattern and remaining condition
     for (auto& cond : conditionList) {
         size_t element = 0;
         std::unique_ptr<RamExpression> lowerExpression;
         std::unique_ptr<RamExpression> upperExpression;
         std::tie(lowerExpression, upperExpression) = getLowerUpperExpression(cond.get(), element, identifier);
         // we have new bounds if at least one is defined
         if (!isRamUndefValue(lowerExpression.get()) || !isRamUndefValue(upperExpression.get())) {
             // if no previous bounds are set then just assign them, consider both bounds to be set (but not
             // necessarily defined) in all remaining cases
             auto type = attributeTypes[element];
             indexable = true;
             if (isRamUndefValue(queryPattern.first[element].get()) &&
                     isRamUndefValue(queryPattern.second[element].get())) {
                 queryPattern.first[element] = std::move(lowerExpression);
                 queryPattern.second[element] = std::move(upperExpression);
                 // if lower bound is undefined and we have a new lower bound then assign it
             } else if (isRamUndefValue(queryPattern.first[element].get()) &&
                        !isRamUndefValue(lowerExpression.get()) && isRamUndefValue(upperExpression.get())) {
                 queryPattern.first[element] = std::move(lowerExpression);
                 // if upper bound is undefined and we have a new upper bound then assign it
             } else if (isRamUndefValue(queryPattern.second[element].get()) &&
                        isRamUndefValue(lowerExpression.get()) && !isRamUndefValue(upperExpression.get())) {
                 queryPattern.second[element] = std::move(upperExpression);
                 // if both bounds are defined ...
                 // and equal then we have a previous equality constraint i.e. Tuple[level, element] = <expr1>
             } else if (!isRamUndefValue(queryPattern.first[element].get()) &&
                        !isRamUndefValue(queryPattern.second[element].get()) &&
                        (*(queryPattern.first[element]) == *(queryPattern.second[element]))) {
                 // new equality constraint i.e. Tuple[level, element] = <expr2>
                 // simply hoist <expr1> = <expr2> to the outer loop
                 if (!isRamUndefValue(lowerExpression.get()) && !isRamUndefValue(upperExpression.get())) {
                     // FIXME: `FEQ` handling; need to know if the expr is a float exp or not
                     addCondition(std::make_unique<RamConstraint>(getEqConstraint(type),
                             souffle::clone(queryPattern.first[element]), std::move(lowerExpression)));
                 }
                 // new lower bound i.e. Tuple[level, element] >= <expr2>
                 // we need to hoist <expr1> >= <expr2> to the outer loop
                 else if (!isRamUndefValue(lowerExpression.get()) && isRamUndefValue(upperExpression.get())) {
                     addCondition(std::make_unique<RamConstraint>(getGreaterEqualConstraint(type),
                             souffle::clone(queryPattern.first[element]), std::move(lowerExpression)));
                 }
                 // new upper bound i.e. Tuple[level, element] <= <expr2>
                 // we need to hoist <expr1> <= <expr2> to the outer loop
                 else if (isRamUndefValue(lowerExpression.get()) && !isRamUndefValue(upperExpression.get())) {
                     addCondition(std::make_unique<RamConstraint>(getLessEqualConstraint(type),
                             souffle::clone(queryPattern.first[element]), std::move(upperExpression)));
                 }
                 // if either bound is defined but they aren't equal we must consider the cases for updating
                 // them note that at this point we know that if we have a lower/upper bound it can't be the
                 // first one
             } else if (!isRamUndefValue(queryPattern.first[element].get()) ||
                        !isRamUndefValue(queryPattern.second[element].get())) {
                 // if we have a new equality constraint and previous inequality constraints
                 if (!isRamUndefValue(lowerExpression.get()) && !isRamUndefValue(upperExpression.get()) &&
                         *lowerExpression == *upperExpression) {
                     // if Tuple[level, element] >= <expr1> and we see Tuple[level, element] = <expr2>
                     // need to hoist <expr2> >= <expr1> to the outer loop
                     if (!isRamUndefValue(queryPattern.first[element].get())) {
                         addCondition(std::make_unique<RamConstraint>(getGreaterEqualConstraint(type),
                                 souffle::clone(lowerExpression), std::move(queryPattern.first[element])));
                     }
                     // if Tuple[level, element] <= <expr1> and we see Tuple[level, element] = <expr2>
                     // need to hoist <expr2> <= <expr1> to the outer loop
                     if (!isRamUndefValue(queryPattern.second[element].get())) {
                         addCondition(std::make_unique<RamConstraint>(getLessEqualConstraint(type),
                                 souffle::clone(upperExpression), std::move(queryPattern.second[element])));
                     }
                     // finally replace bounds with equality constraint
                     queryPattern.first[element] = std::move(lowerExpression);
                     queryPattern.second[element] = std::move(upperExpression);
                     // if we have a new lower bound
                 } else if (!isRamUndefValue(lowerExpression.get())) {
                     // we want the tightest lower bound so we take the max
                     std::vector<std::unique_ptr<RamExpression>> maxArguments;
                     maxArguments.push_back(std::move(queryPattern.first[element]));
                     maxArguments.push_back(std::move(lowerExpression));
                     queryPattern.first[element] =
                             std::make_unique<RamIntrinsicOperator>(getMaxOp(type), std::move(maxArguments));
                     // if we have a new upper bound
                 } else if (!isRamUndefValue(upperExpression.get())) {
                     // we want the tightest upper bound so we take the min
                     std::vector<std::unique_ptr<RamExpression>> minArguments;
                     minArguments.push_back(std::move(queryPattern.second[element]));
                     minArguments.push_back(std::move(upperExpression));
                     queryPattern.second[element] =
                             std::make_unique<RamIntrinsicOperator>(getMinOp(type), std::move(minArguments));
                 }
             }
         } else {
             addCondition(std::move(cond));
         }
     }
     // Avoid null-pointers for condition and query pattern
     if (condition == nullptr) {
         condition = std::make_unique<RamTrue>();
     }
     return condition;
 }
getFloatExpressionPair()
ExpressionPair souffle::MakeIndexTransformer::getFloatExpressionPair (const RamConstraint * binRelOp, size_t & element, int identifier)
Definition at line 192 of file MakeIndex.cpp.
References souffle::clone(), souffle::RamLevelAnalysis::getLevel(), souffle::RamConstraint::getLHS(), souffle::RamConstraint::getOperator(), souffle::RamConstraint::getRHS(), souffle::identifier(), souffle::isGreaterEqualFloat(), souffle::isLessEqualFloat(), lhs, rhs, and rla.
Referenced by getLowerUpperExpression().
{
     if (isLessEqualFloat(binRelOp->getOperator())) {
         // Tuple[level, element] <= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(rhs)};
             }
         }
         // <expr> <= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {clone(lhs), std::make_unique<RamUndefValue>()};
             }
         }
     }
     if (isGreaterEqualFloat(binRelOp->getOperator())) {
         // Tuple[level, element] >= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {clone(rhs), std::make_unique<RamUndefValue>()};
             }
         }
         // <expr> >= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(lhs)};
             }
         }
     }
     return {std::make_unique<RamUndefValue>(), std::make_unique<RamUndefValue>()};
 }
getLowerUpperExpression()
ExpressionPair souffle::MakeIndexTransformer::getLowerUpperExpression (RamCondition * c, size_t & element, int level)
Definition at line 236 of file MakeIndex.cpp.
References souffle::clone(), getFloatExpressionPair(), souffle::RamLevelAnalysis::getLevel(), getSignedExpressionPair(), getUnsignedExpressionPair(), souffle::identifier(), souffle::isEqConstraint(), souffle::isIneqFloat(), souffle::isIneqSigned(), souffle::isIneqUnsigned(), lhs, rhs, and rla.
Referenced by constructPattern().
{
     if (auto* binRelOp = dynamic_cast<RamConstraint*>(c)) {
         if (isEqConstraint(binRelOp->getOperator())) {
             if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
                 const RamExpression* rhs = &binRelOp->getRHS();
                 if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                     element = lhs->getElement();
                     return {clone(rhs), clone(rhs)};
                 }
             }
             if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
                 const RamExpression* lhs = &binRelOp->getLHS();
                 if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                     element = rhs->getElement();
                     return {clone(lhs), clone(lhs)};
                 }
             }
         } else if (isIneqSigned(binRelOp->getOperator())) {
             return getSignedExpressionPair(binRelOp, element, identifier);
         } else if (isIneqUnsigned(binRelOp->getOperator())) {
             return getUnsignedExpressionPair(binRelOp, element, identifier);
         } else if (isIneqFloat(binRelOp->getOperator())) {
             return getFloatExpressionPair(binRelOp, element, identifier);
         }
     }
     return {std::make_unique<RamUndefValue>(), std::make_unique<RamUndefValue>()};
 }
getName()
std::string souffle::MakeIndexTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 66 of file MakeIndex.h.
{
         return "MakeIndexTransformer";
     }
getSignedExpressionPair()
ExpressionPair souffle::MakeIndexTransformer::getSignedExpressionPair (const RamConstraint * binRelOp, size_t & element, int identifier)
Definition at line 44 of file MakeIndex.cpp.
References souffle::ADD, souffle::clone(), souffle::RamLevelAnalysis::getLevel(), souffle::RamConstraint::getLHS(), souffle::RamConstraint::getOperator(), souffle::RamConstraint::getRHS(), souffle::identifier(), souffle::isGreaterEqualSigned(), souffle::isGreaterThanSigned(), souffle::isLessEqualSigned(), souffle::isLessThanSigned(), lhs, rhs, rla, and souffle::SUB.
Referenced by getLowerUpperExpression().
{
     if (isLessEqualSigned(binRelOp->getOperator())) {
         // Tuple[level, element] <= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(rhs)};
             }
         }
         // <expr> <= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {clone(lhs), std::make_unique<RamUndefValue>()};
             }
         }
     }
     if (isGreaterEqualSigned(binRelOp->getOperator())) {
         // Tuple[level, element] >= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {clone(rhs), std::make_unique<RamUndefValue>()};
             }
         }
         // <expr> >= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(lhs)};
             }
         }
     }
     if (isLessThanSigned(binRelOp->getOperator())) {
         // Tuple[level, element] < <expr>
         // is equivalent to
         // Tuple[level, element] <= <expr> - 1
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 std::vector<std::unique_ptr<RamExpression>> expressions;
                 expressions.push_back(clone(rhs));
                 expressions.push_back(std::make_unique<RamSignedConstant>(RamDomain(1)));
                 return {std::make_unique<RamUndefValue>(),
                         std::make_unique<RamIntrinsicOperator>(FunctorOp::SUB, std::move(expressions))};
             }
         }
         // <expr> < Tuple[level, element]
         // is equivalent to
         // <expr> + 1 <= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 std::vector<std::unique_ptr<RamExpression>> expressions;
                 expressions.push_back(souffle::clone(lhs));
                 expressions.push_back(std::make_unique<RamSignedConstant>(RamDomain(1)));
                 return {std::make_unique<RamIntrinsicOperator>(FunctorOp::ADD, std::move(expressions)),
                         std::make_unique<RamUndefValue>()};
             }
         }
     }
     if (isGreaterThanSigned(binRelOp->getOperator())) {
         // Tuple[level, element] > <expr>
         // is equivalent to
         // Tuple[level, element] >= <expr> + 1
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 std::vector<std::unique_ptr<RamExpression>> expressions;
                 expressions.push_back(clone(rhs));
                 expressions.push_back(std::make_unique<RamSignedConstant>(RamDomain(1)));
                 return {std::make_unique<RamIntrinsicOperator>(FunctorOp::ADD, std::move(expressions)),
                         std::make_unique<RamUndefValue>()};
             }
         }
         // <expr> > Tuple[level, element]
         // is equivalent to
         // <expr> - 1 >= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 std::vector<std::unique_ptr<RamExpression>> expressions;
                 expressions.push_back(clone(lhs));
                 expressions.push_back(std::make_unique<RamSignedConstant>(RamDomain(1)));
                 return {std::make_unique<RamUndefValue>(),
                         std::make_unique<RamIntrinsicOperator>(FunctorOp::SUB, std::move(expressions))};
             }
         }
     }
     return {std::make_unique<RamUndefValue>(), std::make_unique<RamUndefValue>()};
 }
getUnsignedExpressionPair()
ExpressionPair souffle::MakeIndexTransformer::getUnsignedExpressionPair (const RamConstraint * binRelOp, size_t & element, int identifier)
Definition at line 151 of file MakeIndex.cpp.
References souffle::clone(), souffle::RamLevelAnalysis::getLevel(), souffle::RamConstraint::getLHS(), souffle::RamConstraint::getOperator(), souffle::RamConstraint::getRHS(), souffle::identifier(), souffle::isGreaterEqualUnsigned(), souffle::isLessEqualUnsigned(), lhs, rhs, and rla.
Referenced by getLowerUpperExpression().
{
     if (isLessEqualUnsigned(binRelOp->getOperator())) {
         // Tuple[level, element] <= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(rhs)};
             }
         }
         // <expr> <= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {clone(lhs), std::make_unique<RamUndefValue>()};
             }
         }
     }
     if (isGreaterEqualUnsigned(binRelOp->getOperator())) {
         // Tuple[level, element] >= <expr>
         if (const auto* lhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getLHS())) {
             const RamExpression* rhs = &binRelOp->getRHS();
             if (lhs->getTupleId() == identifier && rla->getLevel(rhs) < identifier) {
                 element = lhs->getElement();
                 return {clone(rhs), std::make_unique<RamUndefValue>()};
             }
         }
         // <expr> >= Tuple[level, element]
         if (const auto* rhs = dynamic_cast<const RamTupleElement*>(&binRelOp->getRHS())) {
             const RamExpression* lhs = &binRelOp->getLHS();
             if (rhs->getTupleId() == identifier && rla->getLevel(lhs) < identifier) {
                 element = rhs->getElement();
                 return {std::make_unique<RamUndefValue>(), clone(lhs)};
             }
         }
     }
     return {std::make_unique<RamUndefValue>(), std::make_unique<RamUndefValue>()};
 }
makeIndex()
bool souffle::MakeIndexTransformer::makeIndex (RamProgram & program)
Make indexable RAM operation indexed.
Parameters
RAM program that is transformed
Returns
Flag that indicates whether the input program has changed
Definition at line 458 of file MakeIndex.cpp.
References souffle::RamTransformer::apply(), souffle::INFO, souffle::makeLambdaRamMapper(), rewriteAggregate(), rewriteIndexScan(), rewriteScan(), and souffle::visitDepthFirst().
Referenced by transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> scanRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamScan* scan = dynamic_cast<RamScan*>(node.get())) {
                 if (scan->getRelation().getRepresentation() != RelationRepresentation::INFO) {
                     if (std::unique_ptr<RamOperation> op = rewriteScan(scan)) {
                         changed = true;
                         node = std::move(op);
                     }
                 }
             } else if (const RamIndexScan* iscan = dynamic_cast<RamIndexScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = rewriteIndexScan(iscan)) {
                     changed = true;
                     node = std::move(op);
                 }
             } else if (const RamAggregate* agg = dynamic_cast<RamAggregate*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = rewriteAggregate(agg)) {
                     changed = true;
                     node = std::move(op);
                 }
             }
             node->apply(makeLambdaRamMapper(scanRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(scanRewriter));
     });
     return changed;
 }
rewriteAggregate()
std::unique_ptr< RamOperation > souffle::MakeIndexTransformer::rewriteAggregate (const RamAggregate * agg)
Rewrite an aggregate operation to an indexed aggregate operation.
Parameters
Aggregate operation that is potentially rewritten to an indexed version
Returns
The result is null if the aggregate could not be rewritten to an indexed version; otherwise the new indexed version of the aggregate is returned.
Definition at line 382 of file MakeIndex.cpp.
References souffle::clone(), constructPattern(), souffle::RamRelation::getArity(), souffle::RamRelation::getAttributeTypes(), souffle::RamAbstractAggregate::getCondition(), souffle::RamAbstractAggregate::getExpression(), souffle::RamAbstractAggregate::getFunction(), souffle::RamNestedOperation::getOperation(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::identifier(), and souffle::toConjunctionList().
Referenced by makeIndex().
{
     if (dynamic_cast<const RamTrue*>(&agg->getCondition()) == nullptr) {
         const RamRelation& rel = agg->getRelation();
         int identifier = agg->getTupleId();
         RamPattern queryPattern;
         for (unsigned int i = 0; i < rel.getArity(); ++i) {
             queryPattern.first.push_back(std::make_unique<RamUndefValue>());
             queryPattern.second.push_back(std::make_unique<RamUndefValue>());
         }
         bool indexable = false;
         std::unique_ptr<RamCondition> condition = constructPattern(rel.getAttributeTypes(), queryPattern,
                 indexable, toConjunctionList(&agg->getCondition()), identifier);
         if (indexable) {
             return std::make_unique<RamIndexAggregate>(souffle::clone(&agg->getOperation()),
                     agg->getFunction(), std::make_unique<RamRelationReference>(&rel),
                     souffle::clone(&agg->getExpression()), std::move(condition), std::move(queryPattern),
                     agg->getTupleId());
         }
     }
     return nullptr;
 }
rewriteIndexScan()
std::unique_ptr< RamOperation > souffle::MakeIndexTransformer::rewriteIndexScan (const RamIndexScan * iscan)
Rewrite an index scan operation to an amended index scan operation.
Parameters
An IndexScan that can be amended with new index values
Returns
The result is null if the index scan cannot be amended; otherwise the new IndexScan operation is returned.
Definition at line 430 of file MakeIndex.cpp.
References souffle::clone(), constructPattern(), souffle::filter(), souffle::RamRelation::getAttributeTypes(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::identifier(), souffle::isRamTrue(), and souffle::toConjunctionList().
Referenced by makeIndex().
{
     if (const auto* filter = dynamic_cast<const RamFilter*>(&iscan->getOperation())) {
         const RamRelation& rel = iscan->getRelation();
         const int identifier = iscan->getTupleId();
         RamPattern strengthenedPattern;
         strengthenedPattern.first = clone(iscan->getRangePattern().first);
         strengthenedPattern.second = clone(iscan->getRangePattern().second);
         bool indexable = false;
         // strengthen the pattern with construct pattern
         std::unique_ptr<RamCondition> condition = constructPattern(rel.getAttributeTypes(),
                 strengthenedPattern, indexable, toConjunctionList(&filter->getCondition()), identifier);
         if (indexable) {
             // Merge Index Pattern here
             std::unique_ptr<RamOperation> op = souffle::clone(&filter->getOperation());
             if (!isRamTrue(condition.get())) {
                 op = std::make_unique<RamFilter>(std::move(condition), std::move(op));
             }
             return std::make_unique<RamIndexScan>(std::make_unique<RamRelationReference>(&rel), identifier,
                     std::move(strengthenedPattern), std::move(op), iscan->getProfileText());
         }
     }
     return nullptr;
 }
rewriteScan()
std::unique_ptr< RamOperation > souffle::MakeIndexTransformer::rewriteScan (const RamScan * scan)
Rewrite a scan operation to an indexed scan operation.
Parameters
Scan operation that is potentially rewritten to an IndexScan
Returns
The result is null if the scan could not be rewritten to an IndexScan; otherwise the new IndexScan operation is returned.
Definition at line 405 of file MakeIndex.cpp.
References souffle::clone(), constructPattern(), souffle::filter(), souffle::RamRelation::getArity(), souffle::RamRelation::getAttributeTypes(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::identifier(), souffle::isRamTrue(), and souffle::toConjunctionList().
Referenced by makeIndex().
{
     if (const auto* filter = dynamic_cast<const RamFilter*>(&scan->getOperation())) {
         const RamRelation& rel = scan->getRelation();
         const int identifier = scan->getTupleId();
         RamPattern queryPattern;
         for (unsigned int i = 0; i < rel.getArity(); ++i) {
             queryPattern.first.push_back(std::make_unique<RamUndefValue>());
             queryPattern.second.push_back(std::make_unique<RamUndefValue>());
         }
         bool indexable = false;
         std::unique_ptr<RamCondition> condition = constructPattern(rel.getAttributeTypes(), queryPattern,
                 indexable, toConjunctionList(&filter->getCondition()), identifier);
         if (indexable) {
             std::unique_ptr<RamOperation> op = souffle::clone(&filter->getOperation());
             if (!isRamTrue(condition.get())) {
                 op = std::make_unique<RamFilter>(std::move(condition), std::move(op));
             }
             return std::make_unique<RamIndexScan>(std::make_unique<RamRelationReference>(&rel), identifier,
                     std::move(queryPattern), std::move(op), scan->getProfileText());
         }
     }
     return nullptr;
 }
transform()
bool souffle::MakeIndexTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 133 of file MakeIndex.h.
References souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), makeIndex(), and rla.
{
         rla = translationUnit.getAnalysis<RamLevelAnalysis>();
         return makeIndex(translationUnit.getProgram());
     }
Field Documentation
rla
RamLevelAnalysis* souffle::MakeIndexTransformer::rla {nullptr} protected
Definition at line 132 of file MakeIndex.h.
Referenced by getFloatExpressionPair(), getLowerUpperExpression(), getSignedExpressionPair(), getUnsignedExpressionPair(), and transform().
The documentation for this class was generated from the following files:
ram/transform/MakeIndex.h
ram/transform/MakeIndex.cpp