souffle: souffle::RamParallelAggregate Class Reference
souffle::RamParallelAggregate Class Reference
Parallel Aggregation function applied on some relation.
#include <ParallelAggregate.h>
Public Member Functions
RamParallelAggregate * clone () const override
Create a clone (i.e.
RamParallelAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, int ident)
Public Member Functions inherited from souffle::RamAggregate
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, int ident)
Public Member Functions inherited from souffle::RamRelationOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractAggregate
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Get condition.
const RamExpression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
RamAbstractAggregate (AggregateOp fun, std::unique_ptr< RamExpression > expr, std::unique_ptr< RamCondition > cond)
virtual ~RamAbstractAggregate ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamAggregate
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamRelationOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamTupleOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::RamAbstractAggregate
bool equal (const RamNode &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractAggregate
std::unique_ptr< RamCondition > condition
Aggregation tuple condition.
std::unique_ptr< RamExpression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Parallel Aggregation function applied on some relation.
For example:
PARALLEL t0.0 = COUNT FOR ALL t0 IN A
Applies the function PARALLEL COUNT to determine the number of elements in A.
Definition at line 49 of file ParallelAggregate.h.
Constructor & Destructor Documentation
RamParallelAggregate()
souffle::RamParallelAggregate::RamParallelAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, int ident) inline
Definition at line 51 of file ParallelAggregate.h.
Referenced by clone().
             : RamAggregate(std::move(nested), fun, std::move(relRef), std::move(expression),
                       std::move(condition), ident) {}
Member Function Documentation
clone()
RamParallelAggregate* souffle::RamParallelAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamAggregate.
Definition at line 57 of file ParallelAggregate.h.
References souffle::clone(), souffle::RamAbstractAggregate::condition, souffle::RamAbstractAggregate::expression, souffle::RamNestedOperation::getOperation(), souffle::RamTupleOperation::identifier, RamParallelAggregate(), and souffle::RamRelationOperation::relationRef.
{
         return new RamParallelAggregate(souffle::clone(&getOperation()), function,
                 souffle::clone(relationRef), souffle::clone(expression), souffle::clone(condition),
                 identifier);
     }
print()
void souffle::RamParallelAggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamAggregate.
Definition at line 64 of file ParallelAggregate.h.
References souffle::RamAbstractAggregate::condition, souffle::RamAbstractAggregate::getCondition(), souffle::RamRelation::getName(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::isRamTrue(), souffle::RamAbstractAggregate::print(), souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL t" << getTupleId() << ".0=";
         RamAbstractAggregate::print(os, tabpos);
         os << "FOR ALL t" << getTupleId() << "  " << getRelation().getName();
         if (!isRamTrue(condition.get())) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         RamRelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/ParallelAggregate.h