souffle: souffle::RamRelationOperation Class Reference
souffle::RamRelationOperation Class Reference abstract
Abstract class for operations on relations.
#include <RelationOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamRelationOperation * clone () const override=0
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamTupleOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamNestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for operations on relations.
One such operation is a for loop
Definition at line 37 of file RelationOperation.h.
Constructor & Destructor Documentation
RamRelationOperation()
souffle::RamRelationOperation::RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 39 of file RelationOperation.h.
References clone(), and relationRef.
             : RamTupleOperation(ident, std::move(nested), std::move(profileText)),
               relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "relation reference is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::RamRelationOperation::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 53 of file RelationOperation.h.
References souffle::RamNestedOperation::apply(), souffle::map(), and relationRef.
Referenced by souffle::RamChoice::apply(), souffle::RamIndexChoice::apply(), souffle::RamAggregate::apply(), and souffle::RamIndexOperation::apply().
{
         RamTupleOperation::apply(map);
         relationRef = map(std::move(relationRef));
     }
clone()
RamRelationOperation* souffle::RamRelationOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamTupleOperation.
Implemented in souffle::RamIndexOperation, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamAggregate, souffle::RamParallelIndexChoice, souffle::RamIndexAggregate, souffle::RamParallelScan, souffle::RamParallelIndexScan, souffle::RamParallelAggregate, souffle::RamParallelIndexAggregate, souffle::RamIndexScan, souffle::RamParallelChoice, and souffle::RamScan.
Referenced by RamRelationOperation().
equal()
bool souffle::RamRelationOperation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNestedOperation.
Definition at line 65 of file RelationOperation.h.
References souffle::RamTupleOperation::equal(), souffle::equal_ptr(), and relationRef.
Referenced by souffle::RamChoice::equal(), souffle::RamAggregate::equal(), and souffle::RamIndexOperation::equal().
{
         const auto& other = static_cast<const RamRelationOperation&>(node);
         return RamTupleOperation::equal(other) && equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamRelationOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 58 of file RelationOperation.h.
References souffle::RamTupleOperation::getChildNodes(), and relationRef.
Referenced by souffle::RamAggregate::getChildNodes(), and souffle::RamIndexOperation::getChildNodes().
{
         auto res = RamTupleOperation::getChildNodes();
         res.push_back(relationRef.get());
         return res;
     }
getRelation()
const RamRelation& souffle::RamRelationOperation::getRelation () const inline
Get search relation.
Definition at line 49 of file RelationOperation.h.
References relationRef.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::RamScan::print(), souffle::RamParallelChoice::print(), souffle::RamParallelAggregate::print(), souffle::RamParallelScan::print(), souffle::RamIndexScan::print(), souffle::RamParallelIndexAggregate::print(), souffle::RamParallelIndexScan::print(), souffle::RamChoice::print(), souffle::RamAggregate::print(), souffle::RamParallelIndexChoice::print(), souffle::RamIndexAggregate::print(), souffle::RamIndexChoice::print(), souffle::RamIndexOperation::printIndex(), souffle::RamIndexChoice::RamIndexChoice(), souffle::RamIndexOperation::RamIndexOperation(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::NodeGenerator::visitAggregate(), souffle::NodeGenerator::visitChoice(), souffle::NodeGenerator::visitIndexAggregate(), souffle::NodeGenerator::visitParallelAggregate(), souffle::NodeGenerator::visitParallelChoice(), souffle::NodeGenerator::visitParallelIndexAggregate(), souffle::NodeGenerator::visitParallelIndexChoice(), souffle::NodeGenerator::visitParallelIndexScan(), souffle::NodeGenerator::visitParallelScan(), and souffle::NodeGenerator::visitScan().
{
         return *relationRef->get();
     }
Field Documentation
relationRef
std::unique_ptr<RamRelationReference> souffle::RamRelationOperation::relationRef protected
Search relation.
Definition at line 71 of file RelationOperation.h.
Referenced by apply(), souffle::RamScan::clone(), souffle::RamParallelChoice::clone(), souffle::RamIndexScan::clone(), souffle::RamParallelIndexAggregate::clone(), souffle::RamParallelAggregate::clone(), souffle::RamParallelIndexScan::clone(), souffle::RamParallelScan::clone(), souffle::RamIndexAggregate::clone(), souffle::RamParallelIndexChoice::clone(), souffle::RamAggregate::clone(), souffle::RamChoice::clone(), souffle::RamIndexChoice::clone(), souffle::RamIndexOperation::clone(), equal(), getChildNodes(), souffle::RamChoice::getChildNodes(), getRelation(), and RamRelationOperation().
The documentation for this class was generated from the following file:
ram/RelationOperation.h