souffle: souffle::RamAbstractExistenceCheck Class Reference
souffle::RamAbstractExistenceCheck Class Reference
Abstract existence check for a tuple in a relation.
#include <AbstractExistenceCheck.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get relation.
const std::vector< RamExpression * > getValues () const
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
RamAbstractExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamCondition
RamCondition * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Relation.
std::vector< std::unique_ptr< RamExpression > > values
Pattern – nullptr if undefined.
Detailed Description
Abstract existence check for a tuple in a relation.
Definition at line 40 of file AbstractExistenceCheck.h.
Constructor & Destructor Documentation
RamAbstractExistenceCheck()
souffle::RamAbstractExistenceCheck::RamAbstractExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 42 of file AbstractExistenceCheck.h.
References relationRef, and values.
             : relationRef(std::move(relRef)), values(std::move(vals)) {
         assert(relationRef != nullptr && "Relation reference is a nullptr");
         for (const auto& v : values) {
             assert(v != nullptr && "value is a nullptr");
         }
     }
Member Function Documentation
apply()
void souffle::RamAbstractExistenceCheck::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 73 of file AbstractExistenceCheck.h.
References souffle::map(), relationRef, and values.
{
         relationRef = map(std::move(relationRef));
         for (auto& val : values) {
             val = map(std::move(val));
         }
     }
equal()
bool souffle::RamAbstractExistenceCheck::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 94 of file AbstractExistenceCheck.h.
References souffle::equal_ptr(), souffle::equal_targets(), relationRef, and values.
{
         const auto& other = static_cast<const RamAbstractExistenceCheck&>(node);
         return equal_ptr(relationRef, other.relationRef) && equal_targets(values, other.values);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamAbstractExistenceCheck::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 65 of file AbstractExistenceCheck.h.
References relationRef, and values.
{
         std::vector<const RamNode*> res = {relationRef.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
getRelation()
const RamRelation& souffle::RamAbstractExistenceCheck::getRelation () const inline
Get relation.
Definition at line 52 of file AbstractExistenceCheck.h.
References relationRef.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::RamIndexAnalysis::getSearchSignature(), and print().
{
         return *relationRef->get();
     }
getValues()
const std::vector<RamExpression*> souffle::RamAbstractExistenceCheck::getValues () const inline
Get arguments of the tuple/pattern A null pointer element in the vector denotes an unspecified pattern for a tuple element.
Definition at line 61 of file AbstractExistenceCheck.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::RamLevelAnalysis::getLevel(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::RamIndexAnalysis::isTotalSignature(), and souffle::NodeGenerator::visitExistenceCheck().
{
         return toPtrVector(values);
     }
print()
void souffle::RamAbstractExistenceCheck::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Reimplemented in souffle::RamProvenanceExistenceCheck.
Definition at line 81 of file AbstractExistenceCheck.h.
References souffle::RamRelation::getName(), getRelation(), souffle::join(), and values.
Referenced by souffle::RamProvenanceExistenceCheck::print().
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const std::unique_ptr<RamExpression>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") ∈ " << getRelation().getName();
     }
Field Documentation
relationRef
std::unique_ptr<RamRelationReference> souffle::RamAbstractExistenceCheck::relationRef protected
Relation.
Definition at line 100 of file AbstractExistenceCheck.h.
Referenced by apply(), souffle::RamProvenanceExistenceCheck::clone(), souffle::RamExistenceCheck::clone(), equal(), getChildNodes(), getRelation(), and RamAbstractExistenceCheck().
values
std::vector<std::unique_ptr<RamExpression> > souffle::RamAbstractExistenceCheck::values protected
Pattern – nullptr if undefined.
Definition at line 103 of file AbstractExistenceCheck.h.
Referenced by apply(), souffle::RamProvenanceExistenceCheck::clone(), souffle::RamExistenceCheck::clone(), equal(), getChildNodes(), getValues(), print(), and RamAbstractExistenceCheck().
The documentation for this class was generated from the following file:
ram/AbstractExistenceCheck.h