souffle: souffle::MagicSetTransformer::MagicSetCoreTransformer Class Reference
souffle::MagicSetTransformer::MagicSetCoreTransformer Class Reference
Core section of the magic set transformer.
#include <MagicSet.h>
Public Member Functions
MagicSetCoreTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static void addRelevantVariables (std::set< std::string > &variables, const std::vector< const AstBinaryConstraint *> eqConstraints)
Get the closure of the given set of variables under appearance in the given eq constraints.
static std::unique_ptr< AstAtom > createMagicAtom (const AstAtom *atom)
Creates the magic atom associatd with the given (rel, adornment) pair.
static std::unique_ptr< AstClause > createMagicClause (const AstAtom *atom, const std::vector< std::unique_ptr< AstAtom >> &constrainingAtoms, const std::vector< const AstBinaryConstraint *> eqConstraints)
Creates the magic clause centred around the given magic atom.
static std::string getAdornment (const AstQualifiedName &name)
Retrieves an adornment encoded in a given relation name.
static std::vector< const AstBinaryConstraint * > getBindingEqualityConstraints (const AstClause *clause)
Get all potentially-binding equality constraints in a clause.
static AstQualifiedName getMagicName (const AstQualifiedName &name)
Gets a unique magic identifier for a given adorned relation name.
static bool isAdorned (const AstQualifiedName &name)
Checks if a given relation name is adorned.
Detailed Description
Core section of the magic set transformer.
Creates all magic rules and relations based on the preceding adornment, and adds them into rules as needed. Assumes that Normalisation, Labelling, and Adornment have all been performed.
Definition at line 276 of file MagicSet.h.
Member Function Documentation
addRelevantVariables()
void souffle::MagicSetCoreTransformer::addRelevantVariables (std::set< std::string > & variables, const std::vector< const AstBinaryConstraint *> eqConstraints) static private
Get the closure of the given set of variables under appearance in the given eq constraints.
Definition at line 911 of file MagicSet.cpp.
References souffle::contains(), souffle::EQ, souffle::AstVariable::getName(), lhs, rhs, and souffle::visitDepthFirst().
{
     // Helper method to check if all variables in an argument are bound
     auto isFullyBound = [&](const AstArgument* arg) {
         bool fullyBound = true;
         visitDepthFirst(
                 *arg, [&](const AstVariable& var) { fullyBound &= contains(variables, var.getName()); });
         return fullyBound;
     };
     // Helper method to add all newly relevant variables given a lhs = rhs constraint
     auto addLocallyRelevantVariables = [&](const AstArgument* lhs, const AstArgument* rhs) {
         const auto* lhsVar = dynamic_cast<const AstVariable*>(lhs);
         if (lhsVar == nullptr) return true;
         // if the rhs is fully bound, lhs is now bound
         if (!contains(variables, lhsVar->getName())) {
             if (isFullyBound(rhs)) {
                 variables.insert(lhsVar->getName());
                 return false;
             } else {
                 return true;
             }
         }
         // if the rhs is a record, and lhs is a bound var, then all rhs vars are bound
         bool fixpointReached = true;
         if (const auto* rhsRec = dynamic_cast<const AstRecordInit*>(rhs)) {
             for (const auto* arg : rhsRec->getArguments()) {
                 const auto* subVar = dynamic_cast<const AstVariable*>(arg);
                 assert(subVar != nullptr && "expected only variable arguments");
                 if (!contains(variables, subVar->getName())) {
                     fixpointReached = false;
                     variables.insert(subVar->getName());
                 }
             }
         }
         return fixpointReached;
     };
     // Keep adding in relevant variables until we reach a fixpoint
     bool fixpointReached = false;
     while (!fixpointReached) {
         fixpointReached = true;
         for (const auto* eqConstraint : eqConstraints) {
             assert(eqConstraint->getOperator() == BinaryConstraintOp::EQ && "expected only eq constraints");
             fixpointReached &= addLocallyRelevantVariables(eqConstraint->getLHS(), eqConstraint->getRHS());
             fixpointReached &= addLocallyRelevantVariables(eqConstraint->getRHS(), eqConstraint->getLHS());
         }
     }
 }
clone()
MagicSetCoreTransformer* souffle::MagicSetTransformer::MagicSetCoreTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 282 of file MagicSet.h.
References souffle::MagicSetTransformer::transform().
{
         return new MagicSetCoreTransformer();
     }
createMagicAtom()
std::unique_ptr< AstAtom > souffle::MagicSetCoreTransformer::createMagicAtom (const AstAtom * atom) static private
Creates the magic atom associatd with the given (rel, adornment) pair.
Definition at line 895 of file MagicSet.cpp.
References souffle::clone(), souffle::AstAtom::getArguments(), souffle::AstAtom::getQualifiedName(), and i.
{
     auto origRelName = atom->getQualifiedName();
     auto args = atom->getArguments();
     auto magicAtom = std::make_unique<AstAtom>(getMagicName(origRelName));
     auto adornmentMarker = getAdornment(origRelName);
     for (size_t i = 0; i < args.size(); i++) {
         if (adornmentMarker[i] == 'b') {
             magicAtom->addArgument(souffle::clone(args[i]));
         }
     }
     return magicAtom;
 }
createMagicClause()
std::unique_ptr< AstClause > souffle::MagicSetCoreTransformer::createMagicClause (const AstAtom * atom, const std::vector< std::unique_ptr< AstAtom >> & constrainingAtoms, const std::vector< const AstBinaryConstraint *> eqConstraints) static private
Creates the magic clause centred around the given magic atom.
Definition at line 964 of file MagicSet.cpp.
References souffle::clone(), souffle::contains(), souffle::AstVariable::getName(), and souffle::visitDepthFirst().
{
     auto magicHead = createMagicAtom(atom);
     auto magicClause = std::make_unique<AstClause>();
     // Add in all constraining atoms
     for (const auto& bindingAtom : constrainingAtoms) {
         magicClause->addToBody(souffle::clone(bindingAtom));
     }
     // Get the set of all variables that will be relevant to the magic clause
     std::set<std::string> relevantVariables;
     visitDepthFirst(
             constrainingAtoms, [&](const AstVariable& var) { relevantVariables.insert(var.getName()); });
     visitDepthFirst(*magicHead, [&](const AstVariable& var) { relevantVariables.insert(var.getName()); });
     addRelevantVariables(relevantVariables, eqConstraints);
     // Add in all eq constraints containing ONLY relevant variables
     for (const auto* eqConstraint : eqConstraints) {
         bool addConstraint = true;
         visitDepthFirst(*eqConstraint, [&](const AstVariable& var) {
             if (!contains(relevantVariables, var.getName())) {
                 addConstraint = false;
             }
         });
         if (addConstraint) magicClause->addToBody(souffle::clone(eqConstraint));
     }
     magicClause->setHead(std::move(magicHead));
     return magicClause;
 }
getAdornment()
std::string souffle::MagicSetCoreTransformer::getAdornment (const AstQualifiedName & name) static private
Retrieves an adornment encoded in a given relation name.
Definition at line 877 of file MagicSet.cpp.
References souffle::AstQualifiedName::getQualifiers(), and i.
{
     assert(isAdorned(name) && "relation not adorned");
     auto qualifiers = name.getQualifiers();
     auto finalQualifier = qualifiers[qualifiers.size() - 1];
     std::stringstream binding;
     for (size_t i = 1; i < finalQualifier.length() - 1; i++) {
         binding << finalQualifier[i];
     }
     return binding.str();
 }
getBindingEqualityConstraints()
std::vector< const AstBinaryConstraint * > souffle::MagicSetCoreTransformer::getBindingEqualityConstraints (const AstClause * clause) static private
Get all potentially-binding equality constraints in a clause.
Definition at line 998 of file MagicSet.cpp.
References souffle::EQ, souffle::AstClause::getBodyLiterals(), and souffle::visitDepthFirst().
{
     std::vector<const AstBinaryConstraint*> equalityConstraints;
     for (const auto* lit : clause->getBodyLiterals()) {
         const auto* bc = dynamic_cast<const AstBinaryConstraint*>(lit);
         if (bc == nullptr || bc->getOperator() != BinaryConstraintOp::EQ) continue;
         if (dynamic_cast<AstVariable*>(bc->getLHS()) != nullptr ||
                 dynamic_cast<AstConstant*>(bc->getRHS()) != nullptr) {
             bool containsAggrs = false;
             visitDepthFirst(*bc, [&](const AstAggregator& /* aggr */) { containsAggrs = true; });
             if (!containsAggrs) {
                 equalityConstraints.push_back(bc);
             }
         }
     }
     return equalityConstraints;
 }
getMagicName()
AstQualifiedName souffle::MagicSetCoreTransformer::getMagicName (const AstQualifiedName & name) static private
Gets a unique magic identifier for a given adorned relation name.
Definition at line 888 of file MagicSet.cpp.
References souffle::AstQualifiedName::prepend().
{
     assert(isAdorned(name) && "cannot magify unadorned predicates");
     AstQualifiedName magicRelName(name);
     magicRelName.prepend("@magic");
     return magicRelName;
 }
getName()
std::string souffle::MagicSetTransformer::MagicSetCoreTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 278 of file MagicSet.h.
{
         return "MagicSetCoreTransformer";
     }
isAdorned()
bool souffle::MagicSetCoreTransformer::isAdorned (const AstQualifiedName & name) static private
Checks if a given relation name is adorned.
Definition at line 857 of file MagicSet.cpp.
References souffle::AstQualifiedName::getQualifiers(), and i.
{
     // Grab the final qualifier - this is where the adornment is if it exists
     auto qualifiers = name.getQualifiers();
     assert(!qualifiers.empty() && "unexpected empty qualifier list");
     auto finalQualifier = qualifiers[qualifiers.size() - 1];
     assert(finalQualifier.length() > 0 && "unexpected empty qualifier");
     // Pattern: {[bf]*}
     if (finalQualifier[0] == '{' && finalQualifier[finalQualifier.length() - 1] == '}') {
         for (size_t i = 1; i < finalQualifier.length() - 1; i++) {
             char curBindingType = finalQualifier[i];
             if (curBindingType != 'b' && curBindingType != 'f') {
                 return false;
             }
         }
         return true;
     }
     return false;
 }
transform()
bool souffle::MagicSetCoreTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Perform the Magic Set Transformation
Implements souffle::AstTransformer.
Definition at line 1016 of file MagicSet.cpp.
References souffle::clone(), souffle::AstRelation::getAttributes(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), and i.
{
     auto& program = *translationUnit.getProgram();
     std::set<std::unique_ptr<AstClause>> clausesToRemove;
     std::set<std::unique_ptr<AstClause>> clausesToAdd;
     /** Perform the Magic Set Transformation */
     for (const auto* clause : program.getClauses()) {
         clausesToRemove.insert(souffle::clone(clause));
         const auto* head = clause->getHead();
         auto relName = head->getQualifiedName();
         // (1) Add the refined clause
         if (!isAdorned(relName)) {
             // Unadorned relations need not be refined, as every possible tuple is relevant
             clausesToAdd.insert(souffle::clone(clause));
         } else {
             // Refine the clause with a prepended magic atom
             auto magicAtom = createMagicAtom(head);
             auto refinedClause = std::make_unique<AstClause>();
             refinedClause->setHead(souffle::clone(head));
             refinedClause->addToBody(souffle::clone(magicAtom));
             for (auto* literal : clause->getBodyLiterals()) {
                 refinedClause->addToBody(souffle::clone(literal));
             }
             clausesToAdd.insert(std::move(refinedClause));
         }
         // (2) Add the associated magic rules
         std::vector<const AstBinaryConstraint*> eqConstraints = getBindingEqualityConstraints(clause);
         std::vector<std::unique_ptr<AstAtom>> atomsToTheLeft;
         if (isAdorned(relName)) {
             // Add the specialising head atom
             // Output relations are not specialised, and so the head will not contribute to specialisation
             atomsToTheLeft.push_back(createMagicAtom(clause->getHead()));
         }
         for (const auto* lit : clause->getBodyLiterals()) {
             const auto* atom = dynamic_cast<const AstAtom*>(lit);
             if (atom == nullptr) continue;
             if (!isAdorned(atom->getQualifiedName())) {
                 atomsToTheLeft.push_back(souffle::clone(atom));
                 continue;
             }
             // Need to create a magic rule
             auto magicClause = createMagicClause(atom, atomsToTheLeft, eqConstraints);
             atomsToTheLeft.push_back(souffle::clone(atom));
             clausesToAdd.insert(std::move(magicClause));
         }
     }
     for (auto& clause : clausesToAdd) {
         program.addClause(souffle::clone(clause));
     }
     for (const auto& clause : clausesToRemove) {
         program.removeClause(clause.get());
     }
     // Add in the magic relations
     bool changed = false;
     for (const auto* rel : program.getRelations()) {
         const auto& origName = rel->getQualifiedName();
         if (!isAdorned(origName)) continue;
         auto magicRelation = std::make_unique<AstRelation>(getMagicName(origName));
         auto attributes = getRelation(program, origName)->getAttributes();
         auto adornmentMarker = getAdornment(origName);
         for (size_t i = 0; i < attributes.size(); i++) {
             if (adornmentMarker[i] == 'b') {
                 magicRelation->addAttribute(souffle::clone(attributes[i]));
             }
         }
         changed = true;
         program.addRelation(std::move(magicRelation));
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp