souffle: souffle::RamIndexOperation Class Reference
souffle::RamIndexOperation Class Reference
#include <IndexOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamIndexOperation * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< RamExpression * >, std::vector< RamExpression * > > getRangePattern () const
Get range pattern.
void printIndex (std::ostream &os) const
Helper method for printing.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamRelationOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamTupleOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamNestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Definition at line 44 of file IndexOperation.h.
Constructor & Destructor Documentation
RamIndexOperation()
souffle::RamIndexOperation::RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 46 of file IndexOperation.h.
References souffle::RamRelation::getArity(), getRangePattern(), and souffle::RamRelationOperation::getRelation().
Referenced by clone().
             : RamRelationOperation(std::move(r), ident, std::move(nested), std::move(profileText)),
               queryPattern(std::move(queryPattern)) {
         assert(getRangePattern().first.size() == getRelation().getArity() &&
                 getRangePattern().second.size() == getRelation().getArity());
         for (const auto& pattern : queryPattern.first) {
             assert(pattern != nullptr && "pattern is a null-pointer");
         }
         for (const auto& pattern : queryPattern.second) {
             assert(pattern != nullptr && "pattern is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamIndexOperation::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 82 of file IndexOperation.h.
References souffle::RamRelationOperation::apply(), souffle::map(), and queryPattern.
Referenced by souffle::RamIndexAggregate::apply().
{
         RamRelationOperation::apply(map);
         for (auto& pattern : queryPattern.first) {
             pattern = map(std::move(pattern));
         }
         for (auto& pattern : queryPattern.second) {
             pattern = map(std::move(pattern));
         }
     }
clone()
RamIndexOperation* souffle::RamIndexOperation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamRelationOperation.
Reimplemented in souffle::RamParallelIndexChoice, souffle::RamParallelIndexScan, souffle::RamParallelIndexAggregate, and souffle::RamIndexScan.
Definition at line 92 of file IndexOperation.h.
References souffle::clone(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamTupleOperation::getTupleId(), i, queryPattern, RamIndexOperation(), and souffle::RamRelationOperation::relationRef.
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         return new RamIndexOperation(souffle::clone(relationRef), getTupleId(), std::move(resQueryPattern),
                 souffle::clone(&getOperation()), getProfileText());
     }
equal()
bool souffle::RamIndexOperation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 155 of file IndexOperation.h.
References souffle::RamRelationOperation::equal(), souffle::equal_targets(), and queryPattern.
Referenced by souffle::RamIndexAggregate::equal(), and souffle::RamIndexChoice::equal().
{
         const auto& other = static_cast<const RamIndexOperation&>(node);
         return RamRelationOperation::equal(other) &&
                equal_targets(queryPattern.first, other.queryPattern.first) &&
                equal_targets(queryPattern.second, other.queryPattern.second);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamIndexOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 71 of file IndexOperation.h.
References souffle::RamRelationOperation::getChildNodes(), and queryPattern.
Referenced by souffle::RamIndexAggregate::getChildNodes(), and souffle::RamIndexChoice::getChildNodes().
{
         auto res = RamRelationOperation::getChildNodes();
         for (auto& pattern : queryPattern.first) {
             res.push_back(pattern.get());
         }
         for (auto& pattern : queryPattern.second) {
             res.push_back(pattern.get());
         }
         return res;
     }
getRangePattern()
std::pair<std::vector<RamExpression*>, std::vector<RamExpression*> > souffle::RamIndexOperation::getRangePattern () const inline
Get range pattern.
Returns
A pair of std::vector of pointers to RamExpression objects These vectors represent the lower and upper bounds for each attribute in the tuple <expr1> <= Tuple[level, element] <= <expr2> We have that at an index for an attribute, its bounds are <expr1> and <expr2> respectively
Definition at line 67 of file IndexOperation.h.
References queryPattern, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::RamLevelAnalysis::getLevel(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::RamIndexChoice::RamIndexChoice(), RamIndexOperation(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), and souffle::MakeIndexTransformer::rewriteIndexScan().
{
         return std::make_pair(toPtrVector(queryPattern.first), toPtrVector(queryPattern.second));
     }
printIndex()
void souffle::RamIndexOperation::printIndex (std::ostream & os) const inline
Helper method for printing.
Definition at line 105 of file IndexOperation.h.
References souffle::RamRelation::getArity(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::isRamUndefValue(), and queryPattern.
Referenced by souffle::RamIndexScan::print(), souffle::RamParallelIndexAggregate::print(), souffle::RamParallelIndexScan::print(), souffle::RamParallelIndexChoice::print(), souffle::RamIndexAggregate::print(), and souffle::RamIndexChoice::print().
{
         //  const auto& attrib = getRelation().getAttributeNames();
         bool first = true;
         for (unsigned int i = 0; i < getRelation().getArity(); ++i) {
             // TODO: print proper upper lower/bound
             // early exit if no upper/lower bounds are defined
             if (isRamUndefValue(queryPattern.first[i].get()) &&
                     isRamUndefValue(queryPattern.second[i].get())) {
                 continue;
             }
             if (first) {
                 os << " ON INDEX ";
                 first = false;
             } else {
                 os << " AND ";
             }
             // both bounds defined and equal => equality
             if (!isRamUndefValue(queryPattern.first[i].get()) &&
                     !isRamUndefValue(queryPattern.second[i].get())) {
                 // print equality when lower bound = upper bound
                 if (*(queryPattern.first[i]) == *(queryPattern.second[i])) {
                     os << "t" << getTupleId() << ".";
                     os << i << " = ";
                     os << *(queryPattern.first[i]);
                     continue;
                 }
             }
             // at least one bound defined => inequality
             if (!isRamUndefValue(queryPattern.first[i].get()) ||
                     !isRamUndefValue(queryPattern.second[i].get())) {
                 if (!isRamUndefValue(queryPattern.first[i].get())) {
                     os << *(queryPattern.first[i]) << " <= ";
                 }
                 os << "t" << getTupleId() << ".";
                 os << i;
                 if (!isRamUndefValue(queryPattern.second[i].get())) {
                     os << " <= " << *(queryPattern.second[i]);
                 }
                 continue;
             }
         }
     }
Field Documentation
queryPattern
RamPattern souffle::RamIndexOperation::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 163 of file IndexOperation.h.
Referenced by souffle::RamIndexChoice::apply(), apply(), souffle::RamIndexScan::clone(), souffle::RamParallelIndexAggregate::clone(), souffle::RamParallelIndexScan::clone(), souffle::RamIndexAggregate::clone(), souffle::RamParallelIndexChoice::clone(), souffle::RamIndexChoice::clone(), clone(), equal(), getChildNodes(), getRangePattern(), and printIndex().
The documentation for this class was generated from the following file:
ram/IndexOperation.h