souffle: souffle::RamParallelIndexScan Class Reference
souffle::RamParallelIndexScan Class Reference
Search for tuples of a relation matching a criteria.
#include <ParallelIndexScan.h>
Public Member Functions
RamParallelIndexScan * clone () const override
Create a clone (i.e.
RamParallelIndexScan (std::unique_ptr< RamRelationReference > rel, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexScan
RamIndexScan (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< RamExpression * >, std::vector< RamExpression * > > getRangePattern () const
Get range pattern.
void printIndex (std::ostream &os) const
Helper method for printing.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamIndexOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamRelationOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamTupleOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamIndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Search for tuples of a relation matching a criteria.
For example:
QUERY
 ...
   PARALLEL FOR t1 IN X ON INDEX t1.c = t0.0
     ...
Definition at line 53 of file ParallelIndexScan.h.
Constructor & Destructor Documentation
RamParallelIndexScan()
souffle::RamParallelIndexScan::RamParallelIndexScan (std::unique_ptr< RamRelationReference > rel, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 55 of file ParallelIndexScan.h.
Referenced by clone().
             : RamIndexScan(std::move(rel), ident, std::move(queryPattern), std::move(nested), profileText) {}
Member Function Documentation
clone()
RamParallelIndexScan* souffle::RamParallelIndexScan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamIndexScan.
Definition at line 59 of file ParallelIndexScan.h.
References souffle::clone(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamTupleOperation::getTupleId(), i, souffle::RamIndexOperation::queryPattern, RamParallelIndexScan(), and souffle::RamRelationOperation::relationRef.
Referenced by souffle::test::TEST().
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         return new RamParallelIndexScan(souffle::clone(relationRef), getTupleId(), std::move(resQueryPattern),
                 souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::RamParallelIndexScan::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamIndexScan.
Definition at line 72 of file ParallelIndexScan.h.
References souffle::RamRelation::getName(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::RamNestedOperation::print(), souffle::RamIndexOperation::printIndex(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "PARALLEL FOR t" << getTupleId() << " IN ";
         os << rel.getName();
         printIndex(os);
         os << std::endl;
         RamIndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/ParallelIndexScan.h