souffle: souffle::AstBranchDeclaration Class Reference
souffle::AstBranchDeclaration Class Reference
Wrapper for the single branch declaration (product type) inside ADT declaration.
#include <BranchDeclaration.h>
Public Member Functions
AstBranchDeclaration (std::string constructor, VecOwn< AstAttribute > fields, SrcLocation loc={})
AstBranchDeclaration * clone () const override
Create a clone (i.e.
const std::string & getConstructor () const
std::vector< AstAttribute * > getFields ()
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstNode
virtual bool equal (const AstNode &) const
Abstract equality check for two AST nodes.
Private Attributes
std::string constructor
VecOwn< AstAttribute > fields
Detailed Description
Wrapper for the single branch declaration (product type) inside ADT declaration.
Parameters
constructor An entity used to create a variant type. Can be though of as a name of the branch.
fields Branch arguments and their types.
A branch declaration corresponds to a product type and forms a part of ADT declaration. Currently it's required for all the branches to have unique names.
Definition at line 40 of file BranchDeclaration.h.
Constructor & Destructor Documentation
AstBranchDeclaration()
souffle::AstBranchDeclaration::AstBranchDeclaration (std::string constructor, VecOwn< AstAttribute > fields, SrcLocation loc = {}) inline
Definition at line 42 of file BranchDeclaration.h.
References souffle::AstNode::AstNode(), constructor, and fields.
Referenced by clone().
                                                                                                {})
             : AstNode(std::move(loc)), constructor(std::move(constructor)), fields(std::move(fields)){};
Member Function Documentation
clone()
AstBranchDeclaration* souffle::AstBranchDeclaration::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 53 of file BranchDeclaration.h.
References AstBranchDeclaration(), souffle::clone(), and souffle::AstNode::getSrcLoc().
{
         return new AstBranchDeclaration(constructor, souffle::clone(fields), getSrcLoc());
     }
getConstructor()
const std::string& souffle::AstBranchDeclaration::getConstructor () const inline
Definition at line 45 of file BranchDeclaration.h.
References constructor.
{
         return constructor;
     }
getFields()
std::vector<AstAttribute*> souffle::AstBranchDeclaration::getFields () inline
Definition at line 49 of file BranchDeclaration.h.
References souffle::toPtrVector().
{
         return toPtrVector(fields);
     }
print()
void souffle::AstBranchDeclaration::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 58 of file BranchDeclaration.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format("%s {%s}", constructor, join(fields, ", "));
     }
Field Documentation
constructor
std::string souffle::AstBranchDeclaration::constructor private
Definition at line 63 of file BranchDeclaration.h.
Referenced by AstBranchDeclaration(), and getConstructor().
fields
VecOwn<AstAttribute> souffle::AstBranchDeclaration::fields private
Definition at line 64 of file BranchDeclaration.h.
Referenced by AstBranchDeclaration().
The documentation for this class was generated from the following file:
ast/BranchDeclaration.h