souffle: souffle::AstTransformer Class Reference
souffle::AstTransformer Class Reference abstract
#include <Transformer.h>
Public Member Functions
bool apply (AstTranslationUnit &translationUnit)
virtual AstTransformer * clone () const =0
virtual std::string getName () const =0
virtual ~AstTransformer ()=default
Private Member Functions
virtual bool transform (AstTranslationUnit &translationUnit)=0
Detailed Description
Definition at line 25 of file Transformer.h.
Constructor & Destructor Documentation
~AstTransformer()
virtual souffle::AstTransformer::~AstTransformer () virtual default
Member Function Documentation
apply()
bool souffle::AstTransformer::apply (AstTranslationUnit & translationUnit)
Definition at line 23 of file Transformer.cpp.
References souffle::ErrorReport::exitIfErrors(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::invalidateAnalyses(), and transform().
Referenced by souffle::MetaTransformer::applySubtransformer().
{
     // invoke the transformation
     bool changed = transform(translationUnit);
     if (changed) {
         translationUnit.invalidateAnalyses();
     }
     /* Abort evaluation of the program if errors were encountered */
     translationUnit.getErrorReport().exitIfErrors();
     return changed;
 }
clone()
virtual AstTransformer* souffle::AstTransformer::clone () const pure virtual
Implemented in souffle::MagicSetTransformer::MagicSetCoreTransformer, souffle::MagicSetTransformer::AdornDatabaseTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer, souffle::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::MagicSetTransformer, souffle::DebugReporter, souffle::ResolveAliasesTransformer, souffle::FoldAnonymousRecords, souffle::NullTransformer, souffle::MetaTransformer, souffle::MaterializeAggregationQueriesTransformer, souffle::RemoveRelationCopiesTransformer, souffle::IOAttributesTransformer, souffle::PartitionBodyLiteralsTransformer, souffle::AstComponentChecker, souffle::RemoveEmptyRelationsTransformer, souffle::ResolveAnonymousRecordAliases, souffle::AddNullariesToAtomlessAggregatesTransformer, souffle::MinimiseProgramTransformer, souffle::MaterializeSingletonAggregationTransformer, souffle::NameUnnamedVariablesTransformer, souffle::IODefaultsTransformer, souffle::PolymorphicObjectsTransformer, souffle::RemoveTypecastsTransformer, souffle::NormaliseConstraintsTransformer, souffle::ReduceExistentialsTransformer, souffle::AstUserDefinedFunctorsTransformer, souffle::RemoveRedundantSumsTransformer, souffle::GroundedTermsChecker, souffle::InlineRelationsTransformer, souffle::ProvenanceTransformer, souffle::ReplaceSingletonVariablesTransformer, souffle::RemoveBooleanConstraintsTransformer, souffle::AstSemanticChecker, souffle::RemoveRedundantRelationsTransformer, souffle::ReorderLiteralsTransformer, souffle::UniqueAggregationVariablesTransformer, souffle::ADTtoRecordsTransformer, souffle::AstExecutionPlanChecker, souffle::AstPragmaChecker, and souffle::ComponentInstantiationTransformer.
getName()
virtual std::string souffle::AstTransformer::getName () const pure virtual
Implemented in souffle::MagicSetTransformer::MagicSetCoreTransformer, souffle::MagicSetTransformer::AdornDatabaseTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer, souffle::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::MagicSetTransformer, souffle::DebugReporter, souffle::FoldAnonymousRecords, souffle::NullTransformer, souffle::IOAttributesTransformer, souffle::PartitionBodyLiteralsTransformer, souffle::AstComponentChecker, souffle::ResolveAnonymousRecordAliases, souffle::AddNullariesToAtomlessAggregatesTransformer, souffle::MaterializeSingletonAggregationTransformer, souffle::NameUnnamedVariablesTransformer, souffle::IODefaultsTransformer, souffle::MaterializeAggregationQueriesTransformer, souffle::MinimiseProgramTransformer, souffle::PolymorphicObjectsTransformer, souffle::RemoveRelationCopiesTransformer, souffle::RemoveTypecastsTransformer, souffle::NormaliseConstraintsTransformer, souffle::ReduceExistentialsTransformer, souffle::ResolveAliasesTransformer, souffle::AstUserDefinedFunctorsTransformer, souffle::RemoveRedundantSumsTransformer, souffle::InlineRelationsTransformer, souffle::ProvenanceTransformer, souffle::ReplaceSingletonVariablesTransformer, souffle::RemoveBooleanConstraintsTransformer, souffle::RemoveEmptyRelationsTransformer, souffle::AstSemanticChecker, souffle::RemoveRedundantRelationsTransformer, souffle::ReorderLiteralsTransformer, souffle::UniqueAggregationVariablesTransformer, souffle::ADTtoRecordsTransformer, souffle::AstExecutionPlanChecker, souffle::GroundedTermsChecker, souffle::AstPragmaChecker, and souffle::ComponentInstantiationTransformer.
Referenced by souffle::MetaTransformer::applySubtransformer().
transform()
virtual bool souffle::AstTransformer::transform (AstTranslationUnit & translationUnit) private pure virtual
Implemented in souffle::MagicSetTransformer::MagicSetCoreTransformer, souffle::MagicSetTransformer::AdornDatabaseTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::PositiveLabellingTransformer, souffle::MagicSetTransformer::LabelDatabaseTransformer::NegativeLabellingTransformer, souffle::MagicSetTransformer::NormaliseDatabaseTransformer, souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::MagicSetTransformer, souffle::DebugReporter, souffle::ResolveAliasesTransformer, souffle::FoldAnonymousRecords, souffle::MaterializeAggregationQueriesTransformer, souffle::RemoveRelationCopiesTransformer, souffle::IOAttributesTransformer, souffle::PartitionBodyLiteralsTransformer, souffle::AstComponentChecker, souffle::RemoveEmptyRelationsTransformer, souffle::ResolveAnonymousRecordAliases, souffle::AddNullariesToAtomlessAggregatesTransformer, souffle::MinimiseProgramTransformer, souffle::MaterializeSingletonAggregationTransformer, souffle::NameUnnamedVariablesTransformer, souffle::IODefaultsTransformer, souffle::PolymorphicObjectsTransformer, souffle::NormaliseConstraintsTransformer, souffle::ReduceExistentialsTransformer, souffle::AstUserDefinedFunctorsTransformer, souffle::RemoveRedundantSumsTransformer, souffle::GroundedTermsChecker, souffle::InlineRelationsTransformer, souffle::ProvenanceTransformer, souffle::ReplaceSingletonVariablesTransformer, souffle::RemoveBooleanConstraintsTransformer, souffle::AstSemanticChecker, souffle::RemoveRedundantRelationsTransformer, souffle::ReorderLiteralsTransformer, souffle::UniqueAggregationVariablesTransformer, souffle::ADTtoRecordsTransformer, souffle::AstExecutionPlanChecker, souffle::AstPragmaChecker, souffle::ComponentInstantiationTransformer, souffle::NullTransformer, and souffle::RemoveTypecastsTransformer.
Referenced by apply().
The documentation for this class was generated from the following files:
ast/transform/Transformer.h
ast/transform/Transformer.cpp