souffle: souffle::RamTupleElement Class Reference
souffle::RamTupleElement Class Reference
Access element from the current tuple in a tuple environment.
#include <TupleElement.h>
Public Member Functions
RamTupleElement * clone () const override
Create a clone (i.e.
size_t getElement () const
Get element.
int getTupleId () const
Get identifier.
RamTupleElement (size_t ident, size_t elem)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const size_t element
Element number.
const size_t identifier
Identifier for the tuple.
Detailed Description
Access element from the current tuple in a tuple environment.
In the following example, the tuple element t0.1 is accessed:
IF t0.1 in A
    ...
Definition at line 36 of file TupleElement.h.
Constructor & Destructor Documentation
RamTupleElement()
souffle::RamTupleElement::RamTupleElement (size_t ident, size_t elem) inline
Definition at line 38 of file TupleElement.h.
Referenced by clone().
 : identifier(ident), element(elem) {}
Member Function Documentation
clone()
RamTupleElement* souffle::RamTupleElement::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamExpression.
Definition at line 49 of file TupleElement.h.
References element, identifier, and RamTupleElement().
Referenced by souffle::test::TEST().
{
         return new RamTupleElement(identifier, element);
     }
equal()
bool souffle::RamTupleElement::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 58 of file TupleElement.h.
References element, and identifier.
{
         const auto& other = static_cast<const RamTupleElement&>(node);
         return identifier == other.identifier && element == other.element;
     }
getElement()
size_t souffle::RamTupleElement::getElement () const inline
Get element.
Definition at line 45 of file TupleElement.h.
References element.
Referenced by souffle::Synthesiser::emitCode().
{
         return element;
     }
getTupleId()
int souffle::RamTupleElement::getTupleId () const inline
Get identifier.
Definition at line 40 of file TupleElement.h.
References identifier.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), and souffle::ChoiceConversionTransformer::rewriteScan().
{
         return identifier;
     }
print()
void souffle::RamTupleElement::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 54 of file TupleElement.h.
References element, and identifier.
{
         os << "t" << identifier << "." << element;
     }
Field Documentation
element
const size_t souffle::RamTupleElement::element protected
Element number.
Definition at line 67 of file TupleElement.h.
Referenced by clone(), equal(), getElement(), and print().
identifier
const size_t souffle::RamTupleElement::identifier protected
Identifier for the tuple.
Definition at line 64 of file TupleElement.h.
Referenced by clone(), equal(), getTupleId(), and print().
The documentation for this class was generated from the following file:
ram/TupleElement.h