souffle: souffle::RamSubroutineReturn Class Reference
souffle::RamSubroutineReturn Class Reference
A statement for returning from a ram subroutine.
#include <SubroutineReturn.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamSubroutineReturn * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getValues () const
Getter for expressions.
RamSubroutineReturn (std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > expressions
Return expressions.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
A statement for returning from a ram subroutine.
For example:
...
  RETURN (t0.0, t0.1)
Definition at line 42 of file SubroutineReturn.h.
Constructor & Destructor Documentation
RamSubroutineReturn()
souffle::RamSubroutineReturn::RamSubroutineReturn (std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 44 of file SubroutineReturn.h.
References expressions.
Referenced by clone().
                                                                       : expressions(std::move(vals)) {
         for (const auto& expr : expressions) {
             assert(expr != nullptr && "Expression is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamSubroutineReturn::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 71 of file SubroutineReturn.h.
References expressions, and souffle::map().
{
         for (auto& expr : expressions) {
             expr = map(std::move(expr));
         }
     }
clone()
RamSubroutineReturn* souffle::RamSubroutineReturn::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 63 of file SubroutineReturn.h.
References expressions, and RamSubroutineReturn().
Referenced by souffle::test::TEST().
{
         std::vector<std::unique_ptr<RamExpression>> newValues;
         for (auto& expr : expressions) {
             newValues.emplace_back(expr->clone());
         }
         return new RamSubroutineReturn(std::move(newValues));
     }
equal()
bool souffle::RamSubroutineReturn::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 90 of file SubroutineReturn.h.
References souffle::equal_targets(), and expressions.
{
         const auto& other = static_cast<const RamSubroutineReturn&>(node);
         return equal_targets(expressions, other.expressions);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamSubroutineReturn::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 55 of file SubroutineReturn.h.
References expressions.
{
         std::vector<const RamNode*> res;
         for (const auto& expr : expressions) {
             res.push_back(expr.get());
         }
         return res;
     }
getValues()
std::vector<RamExpression*> souffle::RamSubroutineReturn::getValues () const inline
Getter for expressions.
Definition at line 51 of file SubroutineReturn.h.
References expressions, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), print(), and souffle::NodeGenerator::visitSubroutineReturn().
{
         return toPtrVector(expressions);
     }
print()
void souffle::RamSubroutineReturn::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamOperation.
Definition at line 78 of file SubroutineReturn.h.
References getValues(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "RETURN (";
         for (auto val : getValues()) {
             os << *val;
             if (val != *(getValues().end() - 1)) {
                 os << ", ";
             }
         }
         os << ")" << std::endl;
     }
Field Documentation
expressions
std::vector<std::unique_ptr<RamExpression> > souffle::RamSubroutineReturn::expressions protected
Return expressions.
Definition at line 96 of file SubroutineReturn.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getValues(), and RamSubroutineReturn().
The documentation for this class was generated from the following file:
ram/SubroutineReturn.h