souffle: souffle::ClauseNormalisationAnalysis Class Reference
souffle::ClauseNormalisationAnalysis Class Reference
#include <ClauseNormalisation.h>
Public Member Functions
ClauseNormalisationAnalysis ()
const NormalisedClause & getNormalisation (const AstClause *clause) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "clause-normalisation"
Private Attributes
std::map< const AstClause *, NormalisedClause > normalisations
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 85 of file ClauseNormalisation.h.
Constructor & Destructor Documentation
ClauseNormalisationAnalysis()
souffle::ClauseNormalisationAnalysis::ClauseNormalisationAnalysis () inline
Definition at line 89 of file ClauseNormalisation.h.
 : AstAnalysis(name) {}
Member Function Documentation
getNormalisation()
const NormalisedClause & souffle::ClauseNormalisationAnalysis::getNormalisation (const AstClause * clause) const
Definition at line 173 of file ClauseNormalisation.cpp.
References souffle::contains().
Referenced by souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses().
{
     assert(contains(normalisations, clause) && "clause not normalised");
     return normalisations.at(clause);
 }
print()
void souffle::ClauseNormalisationAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 159 of file ClauseNormalisation.cpp.
References i.
{
     for (const auto& [clause, norm] : normalisations) {
         os << "Normalise(" << *clause << ") = {";
         const auto& els = norm.getElements();
         for (size_t i = 0; i < els.size(); i++) {
             if (i != 0) {
                 os << ", ";
             }
             os << els[i].name << ":" << els[i].params;
         }
         os << "}" << std::endl;
     }
 }
run()
void souffle::ClauseNormalisationAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 151 of file ClauseNormalisation.cpp.
References souffle::contains(), souffle::AstTranslationUnit::getProgram(), and souffle::NormalisedClause::NormalisedClause().
{
     const auto& program = *translationUnit.getProgram();
     for (const auto* clause : program.getClauses()) {
         assert(!contains(normalisations, clause) && "clause already processed");
         normalisations[clause] = NormalisedClause(clause);
     }
 }
Field Documentation
name
constexpr const char* souffle::ClauseNormalisationAnalysis::name = "clause-normalisation" static
Definition at line 87 of file ClauseNormalisation.h.
normalisations
std::map<const AstClause*, NormalisedClause> souffle::ClauseNormalisationAnalysis::normalisations private
Definition at line 98 of file ClauseNormalisation.h.
The documentation for this class was generated from the following files:
ast/analysis/ClauseNormalisation.h
ast/analysis/ClauseNormalisation.cpp