souffle: souffle::AstVariable Class Reference
souffle::AstVariable Class Reference
Named variable class.
#include <Variable.h>
Public Member Functions
AstVariable (std::string name, SrcLocation loc={})
AstVariable * clone () const override
Create clone.
const std::string & getName () const
Return variable name.
void setName (std::string name)
Set variable name.
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::string name
Name.
Detailed Description
Named variable class.
Definition at line 32 of file Variable.h.
Constructor & Destructor Documentation
AstVariable()
souffle::AstVariable::AstVariable (std::string name, SrcLocation loc = {}) inline
Definition at line 34 of file Variable.h.
References name.
Referenced by clone().
                                                   {})
             : AstArgument(std::move(loc)), name(std::move(name)) {}
Member Function Documentation
clone()
AstVariable* souffle::AstVariable::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 47 of file Variable.h.
References AstVariable(), and souffle::AstNode::getSrcLoc().
{
         return new AstVariable(name, getSrcLoc());
     }
equal()
bool souffle::AstVariable::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 56 of file Variable.h.
References name.
{
         const auto& other = static_cast<const AstVariable&>(node);
         return name == other.name;
     }
getName()
const std::string& souffle::AstVariable::getName () const inline
Return variable name.
Definition at line 43 of file Variable.h.
References name.
Referenced by souffle::MagicSetTransformer::MagicSetCoreTransformer::addRelevantVariables(), souffle::AstToRamTranslator::ValueIndex::addVarReference(), souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstSemanticCheckerImpl::checkComplexRule(), souffle::MagicSetTransformer::MagicSetCoreTransformer::createMagicClause(), souffle::MaterializeSingletonAggregationTransformer::findUniqueVariableName(), souffle::ResolveAnonymousRecordAliases::findVariablesRecordMapping(), souffle::AstToRamTranslator::ValueIndex::getDefinitionPoint(), souffle::getSipsFunction(), souffle::AstToRamTranslator::ValueIndex::isDefined(), souffle::MaterializeSingletonAggregationTransformer::isSingleValued(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::numBoundArguments(), souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::processEqualityBindings(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::TypeChecker::visitVariable().
{
         return name;
     }
print()
void souffle::AstVariable::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 52 of file Variable.h.
References name.
{
         os << name;
     }
setName()
void souffle::AstVariable::setName (std::string name) inline
Set variable name.
Definition at line 38 of file Variable.h.
{
         this->name = std::move(name);
     }
Field Documentation
name
std::string souffle::AstVariable::name protected
Name.
Definition at line 62 of file Variable.h.
Referenced by AstVariable(), equal(), getName(), and print().
The documentation for this class was generated from the following file:
ast/Variable.h