souffle: souffle::MinIndexSelection Class Reference
souffle::MinIndexSelection Class Reference
computes the minimal index cover for a relation in a RAM Program.
#include <Index.h>
Data Structures
class SearchComparator
Public Types
using AttributeIndex = uint32_t
using AttributeSet = std::unordered_set< AttributeIndex >
using Chain = std::vector< SearchSignature >
using ChainOrderMap = std::list< Chain >
using DischargeMap = std::unordered_map< SearchSignature, AttributeSet, SearchSignature::Hasher >
using IndexSignatureMap = std::unordered_map< AttributeIndex, SearchSignature >
using LexOrder = std::vector< AttributeIndex >
using OrderCollection = std::vector< LexOrder >
using SearchSet = std::set< SearchSignature, SearchComparator >
using SignatureIndexMap = std::unordered_map< SearchSignature, AttributeIndex, SearchSignature::Hasher >
using SignatureMap = std::unordered_map< SearchSignature, SearchSignature, SearchSignature::Hasher >
Public Member Functions
void addSearch (SearchSignature cols)
Add new key to an Index Set
const ChainOrderMap getAllChains () const
Get all chains
const OrderCollection getAllOrders () const
Get all indexes
AttributeSet getAttributesToDischarge (const SearchSignature &s, const RamRelation &rel)
Return the attribute position for each indexed operation that should be discharged.
const LexOrder & getLexOrder (SearchSignature cols) const
Get index for a search
int getLexOrderNum (SearchSignature cols) const
Get index for a search
const SearchSet & getSearches () const
Get searches
void insertDefaultTotalIndex (size_t arity)
insert a total order index
bool isSubset (SearchSignature cols) const
Check whether number of constraints in k is not equal to number of columns in lexicographical order.
MinIndexSelection ()=default
void solve ()
map the keys in the key set to lexicographical order
~MinIndexSelection ()=default
Protected Member Functions
Chain getChain (const SearchSignature umn, const MaxMatching::Matchings &match)
get a chain from a matching
const ChainOrderMap getChainsFromMatching (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all chains from the matching
const SearchSet getUnmatchedKeys (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all nodes which are unmatched from A-> B
void insertIndex (LexOrder &ids, SearchSignature delta)
insert an index based on the delta
int map (SearchSignature cols) const
maps search columns to an lexicographical order (labeled by a number)
void removeExtraInequalities ()
remove arbitrary extra inequalities
void updateSearch (SearchSignature oldSearch, SearchSignature newSearch)
Static Protected Member Functions
static size_t card (SearchSignature cols)
count the number of constraints in key
Protected Attributes
ChainOrderMap chainToOrder
DischargeMap dischargedMap
IndexSignatureMap indexToSignature
MaxMatching matching
OrderCollection orders
SearchSet searches
SignatureIndexMap signatureToIndexA
SignatureIndexMap signatureToIndexB
Detailed Description
computes the minimal index cover for a relation in a RAM Program.
If the indexes of a relation can cover several searches, the minimal set of indexes is computed by Dilworth's problem. See
"Automatic Index Selection for Large-Scale Datalog Computation" http://www.vldb.org/pvldb/vol12/p141-subotic.pdf
Definition at line 212 of file Index.h.
Member Typedef Documentation
AttributeIndex
using souffle::MinIndexSelection::AttributeIndex = uint32_t
Definition at line 214 of file Index.h.
AttributeSet
using souffle::MinIndexSelection::AttributeSet = std::unordered_set<AttributeIndex>
Definition at line 215 of file Index.h.
Chain
using souffle::MinIndexSelection::Chain = std::vector<SearchSignature>
Definition at line 222 of file Index.h.
ChainOrderMap
using souffle::MinIndexSelection::ChainOrderMap = std::list<Chain>
Definition at line 225 of file Index.h.
DischargeMap
using souffle::MinIndexSelection::DischargeMap = std::unordered_map<SearchSignature, AttributeSet, SearchSignature::Hasher>
Definition at line 219 of file Index.h.
IndexSignatureMap
using souffle::MinIndexSelection::IndexSignatureMap = std::unordered_map<AttributeIndex, SearchSignature>
Definition at line 218 of file Index.h.
LexOrder
using souffle::MinIndexSelection::LexOrder = std::vector<AttributeIndex>
Definition at line 220 of file Index.h.
OrderCollection
using souffle::MinIndexSelection::OrderCollection = std::vector<LexOrder>
Definition at line 221 of file Index.h.
SearchSet
using souffle::MinIndexSelection::SearchSet = std::set<SearchSignature, SearchComparator>
Definition at line 235 of file Index.h.
SignatureIndexMap
using souffle::MinIndexSelection::SignatureIndexMap = std::unordered_map<SearchSignature, AttributeIndex, SearchSignature::Hasher>
Definition at line 217 of file Index.h.
SignatureMap
using souffle::MinIndexSelection::SignatureMap = std::unordered_map<SearchSignature, SearchSignature, SearchSignature::Hasher>
Definition at line 216 of file Index.h.
Constructor & Destructor Documentation
MinIndexSelection()
souffle::MinIndexSelection::MinIndexSelection () default
~MinIndexSelection()
souffle::MinIndexSelection::~MinIndexSelection () default
Member Function Documentation
addSearch()
void souffle::MinIndexSelection::addSearch (SearchSignature cols) inline
Add new key to an Index Set
Definition at line 241 of file Index.h.
References souffle::SearchSignature::empty().
Referenced by souffle::RamIndexAnalysis::run(), and souffle::TEST().
{
         if (!cols.empty()) {
             searches.insert(cols);
         }
     }
card()
static size_t souffle::MinIndexSelection::card (SearchSignature cols) inline static protected
count the number of constraints in key
Definition at line 317 of file Index.h.
References souffle::SearchSignature::arity(), i, and souffle::None.
{
         size_t sz = 0;
         for (size_t i = 0; i < cols.arity(); i++) {
             if (cols[i] != AttributeConstraint::None) {
                 sz++;
             }
         }
         return sz;
     }
getAllChains()
const ChainOrderMap souffle::MinIndexSelection::getAllChains () const inline
Get all chains
Definition at line 272 of file Index.h.
Referenced by souffle::RamIndexAnalysis::print().
{
         return chainToOrder;
     }
getAllOrders()
const OrderCollection souffle::MinIndexSelection::getAllOrders () const inline
Get all indexes
Definition at line 267 of file Index.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::InterpreterRelation::InterpreterRelation(), souffle::RamIndexAnalysis::print(), and souffle::RamIndexAnalysis::run().
{
         return orders;
     }
getAttributesToDischarge()
MinIndexSelection::AttributeSet souffle::MinIndexSelection::getAttributesToDischarge (const SearchSignature & s, const RamRelation & rel)
Return the attribute position for each indexed operation that should be discharged.
Definition at line 436 of file Index.cpp.
References souffle::SearchSignature::arity(), souffle::BTREE, souffle::Global::config(), souffle::DEFAULT, souffle::RamRelation::getRepresentation(), i, and souffle::Inequal.
Referenced by souffle::IndexedInequalityTransformer::transformIndexToFilter().
{
     // by default we have all attributes w/inequalities discharged
     AttributeSet allInequalities;
     for (size_t i = 0; i < s.arity(); ++i) {
         if (s[i] == AttributeConstraint::Inequal) {
             allInequalities.insert(i);
         }
     }
     // if we don't have a btree then we don't retain any inequalities
     if (rel.getRepresentation() != RelationRepresentation::BTREE &&
             rel.getRepresentation() != RelationRepresentation::DEFAULT) {
         return allInequalities;
     }
     // do not support indexed inequalities with provenance
     if (Global::config().has("provenance")) {
         return allInequalities;
     }
     return dischargedMap[s];
 }
getChain()
MinIndexSelection::Chain souffle::MinIndexSelection::getChain (const SearchSignature umn, const MaxMatching::Matchings & match) protected
get a chain from a matching
Parameters
Starting node of a chain
Matching
Returns
A minimal chain given an unmapped node from set A we follow it from set B until it cannot be matched from B if not matched from B then umn is a chain.
Definition at line 337 of file Index.cpp.
{
     SearchSignature start = umn;  // start at an unmatched node
     Chain chain;
     // given an unmapped node from set A we follow it from set B until it cannot be matched from B
     //  if not mateched from B then umn is a chain
     //
     // Assume : no circular mappings, i.e. a in A -> b in B -> ........ -> a in A is not allowed.
     // Given this, the loop will terminate
     while (true) {
         auto mit = match.find(signatureToIndexB[start]);  // we start from B side
         // on each iteration we swap sides when collecting the chain so we use the corresponding index map
         if (std::find(chain.begin(), chain.end(), start) == chain.end()) {
             chain.push_back(start);
         }
         if (mit == match.end()) {
             std::reverse(chain.begin(), chain.end());
             return chain;
         }
         SearchSignature a = indexToSignature.at(mit->second);
         if (std::find(chain.begin(), chain.end(), a) == chain.end()) {
             chain.push_back(a);
         }
         start = a;
     }
 }
getChainsFromMatching()
const MinIndexSelection::ChainOrderMap souffle::MinIndexSelection::getChainsFromMatching (const MaxMatching::Matchings & match, const SearchSet & nodes) protected
get all chains from the matching
Definition at line 366 of file Index.cpp.
{
     assert(!nodes.empty());
     // Get all unmatched nodes from A
     const SearchSet& umKeys = getUnmatchedKeys(match, nodes);
     // Case: if no unmatched nodes then we have an anti-chain
     if (umKeys.empty()) {
         for (auto node : nodes) {
             Chain a;
             a.push_back(node);
             chainToOrder.push_back(a);
             removeExtraInequalities();
             return chainToOrder;
         }
     }
     assert(!umKeys.empty());
     // A worklist of used nodes
     SearchSet usedKeys;
     // Case: nodes < umKeys or if nodes == umKeys then anti chain - this is handled by this loop
     for (auto umKey : umKeys) {
         Chain c = getChain(umKey, match);
         assert(!c.empty());
         chainToOrder.push_back(c);
     }
     assert(!chainToOrder.empty());
     removeExtraInequalities();
     return chainToOrder;
 }
getLexOrder()
const LexOrder& souffle::MinIndexSelection::getLexOrder (SearchSignature cols) const inline
Get index for a search
Definition at line 256 of file Index.h.
References souffle::map().
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), and souffle::SynthesiserBrieRelation::generateTypeStruct().
{
         int idx = map(cols);
         return orders[idx];
     }
getLexOrderNum()
int souffle::MinIndexSelection::getLexOrderNum (SearchSignature cols) const inline
Get index for a search
Definition at line 262 of file Index.h.
References souffle::map().
Referenced by souffle::NodeGenerator::encodeIndexPos().
{
         return map(cols);
     }
getSearches()
const SearchSet& souffle::MinIndexSelection::getSearches () const inline
Get searches
Definition at line 251 of file Index.h.
Referenced by souffle::RamIndexAnalysis::print(), and souffle::RamIndexAnalysis::run().
{
         return searches;
     }
getUnmatchedKeys()
const SearchSet souffle::MinIndexSelection::getUnmatchedKeys (const MaxMatching::Matchings & match, const SearchSet & nodes) inline protected
get all nodes which are unmatched from A-> B
Definition at line 375 of file Index.h.
{
         SearchSet unmatched;
         // For all nodes n such that n is not in match
         for (auto node : nodes) {
             if (match.find(signatureToIndexA[node]) == match.end()) {
                 unmatched.insert(node);
             }
         }
         return unmatched;
     }
insertDefaultTotalIndex()
void souffle::MinIndexSelection::insertDefaultTotalIndex (size_t arity) inline
insert a total order index
Parameters
size of the index
Definition at line 291 of file Index.h.
References souffle::SearchSignature::getFullSearchSignature(), and i.
Referenced by souffle::RamIndexAnalysis::run(), and souffle::test::TEST().
{
         Chain chain = std::vector<SearchSignature>();
         SearchSignature fullIndexKey = SearchSignature::getFullSearchSignature(arity);
         chain.push_back(fullIndexKey);
         chainToOrder.push_back(std::move(chain));
         LexOrder totalOrder;
         for (size_t i = 0; i < arity; ++i) {
             totalOrder.push_back(i);
         }
         orders.push_back(std::move(totalOrder));
     }
insertIndex()
void souffle::MinIndexSelection::insertIndex (LexOrder & ids, SearchSignature delta) inline protected
insert an index based on the delta
Definition at line 341 of file Index.h.
References souffle::SearchSignature::arity(), souffle::Equal, and souffle::Inequal.
{
         LexOrder backlog;  // add inequalities at the end
         for (size_t pos = 0; pos < delta.arity(); pos++) {
             if (delta[pos] == AttributeConstraint::Equal) {
                 ids.push_back(pos);
             } else if (delta[pos] == AttributeConstraint::Inequal) {
                 backlog.push_back(pos);
             }
         }
         ids.insert(ids.end(), backlog.begin(), backlog.end());
     }
isSubset()
bool souffle::MinIndexSelection::isSubset (SearchSignature cols) const inline
Check whether number of constraints in k is not equal to number of columns in lexicographical order.
Definition at line 280 of file Index.h.
References souffle::map().
{
         int idx = map(cols);
         return card(cols) < orders[idx].size();
     }
map()
int souffle::MinIndexSelection::map (SearchSignature cols) const inline protected
maps search columns to an lexicographical order (labeled by a number)
Definition at line 328 of file Index.h.
References souffle::fatal(), and i.
{
         assert(orders.size() == chainToOrder.size() && "Order and Chain Sizes do not match!!");
         int i = 0;
         for (auto it = chainToOrder.begin(); it != chainToOrder.end(); ++it, ++i) {
             if (std::find(it->begin(), it->end(), cols) != it->end()) {
                 assert((size_t)i < orders.size());
                 return i;
             }
         }
         fatal("cannot find matching lexicographical order");
     }
removeExtraInequalities()
void souffle::MinIndexSelection::removeExtraInequalities () protected
remove arbitrary extra inequalities
Definition at line 417 of file Index.cpp.
References i, souffle::Inequal, and souffle::None.
{
     for (auto chain : chainToOrder) {
         for (auto oldSearch : chain) {
             auto newSearch = oldSearch;
             bool seenInequality = false;
             for (size_t i = 0; i < oldSearch.arity(); ++i) {
                 if (oldSearch[i] == AttributeConstraint::Inequal) {
                     if (seenInequality) {
                         newSearch[i] = AttributeConstraint::None;
                     } else {
                         seenInequality = true;
                     }
                 }
             }
             updateSearch(oldSearch, newSearch);
         }
     }
 }
solve()
void souffle::MinIndexSelection::solve ()
map the keys in the key set to lexicographical order
Definition at line 255 of file Index.cpp.
References souffle::Equal, souffle::SearchSignature::getDelta(), i, k, l, souffle::map(), and souffle::None.
Referenced by souffle::RamIndexAnalysis::run(), and souffle::TEST().
{
     // map the keys in the key set to lexicographical order
     if (searches.empty()) {
         return;
     }
     // map the signatures of each search to a unique index for the matching problem
     AttributeIndex currentIndex = 1;
     for (SearchSignature s : searches) {
         if (s.empty()) {
             continue;
         }
         // map the signature to its unique index in each set
         signatureToIndexA.insert({s, currentIndex});
         signatureToIndexB.insert({s, currentIndex + 1});
         // map each index back to the search signature
         indexToSignature.insert({currentIndex, s});
         indexToSignature.insert({currentIndex + 1, s});
         currentIndex += 2;
     }
     // Construct the matching poblem
     for (auto search : searches) {
         for (auto itt : searches) {
             if (search == itt) {
                 continue;
             }
             if (search < itt) {
                 matching.addEdge(signatureToIndexA[search], signatureToIndexB[itt]);
             }
         }
     }
     // Perform the Hopcroft-Karp on the graph and receive matchings (mapped A->B and B->A)
     // Assume: alg.calculate is not called on an empty graph
     assert(!searches.empty());
     const MaxMatching::Matchings& matchings = matching.solve();
     // Extract the chains given the nodes and matchings
     ChainOrderMap chains = getChainsFromMatching(matchings, searches);
     // Should never get no chains back as we never call calculate on an empty graph
     assert(!chains.empty());
     for (const auto& chain : chains) {
         std::vector<uint32_t> ids;
         SearchSignature initDelta = *(chain.begin());
         insertIndex(ids, initDelta);
         // build the lex-order
         for (auto iit = chain.begin(); next(iit) != chain.end(); ++iit) {
             SearchSignature delta = SearchSignature::getDelta(*next(iit), *iit);
             insertIndex(ids, delta);
         }
         assert(!ids.empty());
         orders.push_back(ids);
     }
     // Validate the lex-order
     for (auto chain : chains) {
         for (auto search : chain) {
             int idx = map(search);
             size_t l = card(search);
             SearchSignature k(search.arity());
             for (size_t i = 0; i < l; i++) {
                 k[orders[idx][i]] = AttributeConstraint::Equal;
             }
             for (size_t i = 0; i < search.arity(); ++i) {
                 if (k[i] == AttributeConstraint::None && search[i] != AttributeConstraint::None) {
                     assert("incorrect lexicographical order");
                 }
                 if (k[i] != AttributeConstraint::None && search[i] == AttributeConstraint::None) {
                     assert("incorrect lexicographical order");
                 }
             }
         }
     }
 }
updateSearch()
void souffle::MinIndexSelection::updateSearch (SearchSignature oldSearch, SearchSignature newSearch) protected
Parameters
OldSearch to be updated
NewSearch to replace the OldSearch
Definition at line 400 of file Index.cpp.
References souffle::SearchSignature::getDelta(), i, and souffle::Inequal.
{
     auto delta = SearchSignature::getDelta(oldSearch, newSearch);
     for (size_t i = 0; i < delta.arity(); ++i) {
         if (delta[i] == AttributeConstraint::Inequal) {
             dischargedMap[oldSearch].insert(i);
         }
     }
     for (auto& chain : chainToOrder) {
         for (auto& search : chain) {
             if (search == oldSearch) {
                 search = newSearch;
             }
         }
     }
 }
Field Documentation
chainToOrder
ChainOrderMap souffle::MinIndexSelection::chainToOrder protected
Definition at line 313 of file Index.h.
dischargedMap
DischargeMap souffle::MinIndexSelection::dischargedMap protected
Definition at line 309 of file Index.h.
indexToSignature
IndexSignatureMap souffle::MinIndexSelection::indexToSignature protected
Definition at line 310 of file Index.h.
matching
MaxMatching souffle::MinIndexSelection::matching protected
Definition at line 314 of file Index.h.
Referenced by souffle::TestAutoIndex::getNumMatchings().
orders
OrderCollection souffle::MinIndexSelection::orders protected
Definition at line 312 of file Index.h.
searches
SearchSet souffle::MinIndexSelection::searches protected
Definition at line 311 of file Index.h.
signatureToIndexA
SignatureIndexMap souffle::MinIndexSelection::signatureToIndexA protected
Definition at line 307 of file Index.h.
signatureToIndexB
SignatureIndexMap souffle::MinIndexSelection::signatureToIndexB protected
Definition at line 308 of file Index.h.
The documentation for this class was generated from the following files:
ram/analysis/Index.h
ram/analysis/Index.cpp