souffle: souffle::RemoveEmptyRelationsTransformer Class Reference
souffle::RemoveEmptyRelationsTransformer Class Reference
Transformation pass to remove all empty relations and rules that use empty relations.
#include <RemoveEmptyRelations.h>
Public Member Functions
RemoveEmptyRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static bool removeEmptyRelations (AstTranslationUnit &translationUnit)
Eliminate all empty relations (and their uses) in the given program.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static bool removeEmptyRelationUses (AstTranslationUnit &translationUnit, const AstQualifiedName &emptyRelation)
Eliminate rules that contain empty relations and/or rewrite them.
Detailed Description
Transformation pass to remove all empty relations and rules that use empty relations.
Definition at line 28 of file RemoveEmptyRelations.h.
Member Function Documentation
clone()
RemoveEmptyRelationsTransformer* souffle::RemoveEmptyRelationsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 42 of file RemoveEmptyRelations.h.
{
         return new RemoveEmptyRelationsTransformer();
     }
getName()
std::string souffle::RemoveEmptyRelationsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 30 of file RemoveEmptyRelations.h.
References removeEmptyRelations().
{
         return "RemoveEmptyRelationsTransformer";
     }
removeEmptyRelations()
bool souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations (AstTranslationUnit & translationUnit) static
Eliminate all empty relations (and their uses) in the given program.
Parameters
translationUnit the program to be processed
Returns
whether the program was modified
Definition at line 35 of file RemoveEmptyRelations.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::getAtomRelation(), souffle::AstAggregator::getBodyLiterals(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), removeEmptyRelationUses(), souffle::removeRelation(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     AstProgram& program = *translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     std::set<AstQualifiedName> emptyRelations;
     bool changed = false;
     for (auto rel : program.getRelations()) {
         if (!getClauses(program, *rel).empty() || ioTypes->isInput(rel)) {
             continue;
         }
         emptyRelations.insert(rel->getQualifiedName());
         bool usedInAggregate = false;
         visitDepthFirst(program, [&](const AstAggregator& agg) {
             for (const auto lit : agg.getBodyLiterals()) {
                 visitDepthFirst(*lit, [&](const AstAtom& atom) {
                     if (getAtomRelation(&atom, &program) == rel) {
                         usedInAggregate = true;
                     }
                 });
             }
         });
         if (!usedInAggregate && !ioTypes->isOutput(rel)) {
             removeRelation(translationUnit, rel->getQualifiedName());
             changed = true;
         }
     }
     for (const auto& relName : emptyRelations) {
         changed |= removeEmptyRelationUses(translationUnit, relName);
     }
     return changed;
 }
removeEmptyRelationUses()
bool souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses (AstTranslationUnit & translationUnit, const AstQualifiedName & emptyRelation) static private
Eliminate rules that contain empty relations and/or rewrite them.
Parameters
translationUnit the program to be processed
emptyRelation relation that is empty
Returns
whether the program was modified
Definition at line 70 of file RemoveEmptyRelations.cpp.
References souffle::AstProgram::addClause(), clauses, souffle::clone(), souffle::cloneHead(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::removeClause(), and souffle::visitDepthFirst().
Referenced by removeEmptyRelations(), and transform().
{
     AstProgram& program = *translationUnit.getProgram();
     bool changed = false;
     //
     // (1) drop rules from the program that have empty relations in their bodies.
     // (2) drop negations of empty relations
     //
     // get all clauses
     std::vector<const AstClause*> clauses;
     visitDepthFirst(program, [&](const AstClause& cur) { clauses.push_back(&cur); });
     // clean all clauses
     for (const AstClause* cl : clauses) {
         // check for an atom whose relation is the empty relation
         bool removed = false;
         for (AstLiteral* lit : cl->getBodyLiterals()) {
             if (auto* arg = dynamic_cast<AstAtom*>(lit)) {
                 if (arg->getQualifiedName() == emptyRelationName) {
                     program.removeClause(cl);
                     removed = true;
                     changed = true;
                     break;
                 }
             }
         }
         if (!removed) {
             // check whether a negation with empty relations exists
             bool rewrite = false;
             for (AstLiteral* lit : cl->getBodyLiterals()) {
                 if (auto* neg = dynamic_cast<AstNegation*>(lit)) {
                     if (neg->getAtom()->getQualifiedName() == emptyRelationName) {
                         rewrite = true;
                         break;
                     }
                 }
             }
             if (rewrite) {
                 // clone clause without negation for empty relations
                 auto res = std::unique_ptr<AstClause>(cloneHead(cl));
                 for (AstLiteral* lit : cl->getBodyLiterals()) {
                     if (auto* neg = dynamic_cast<AstNegation*>(lit)) {
                         if (neg->getAtom()->getQualifiedName() != emptyRelationName) {
                             res->addToBody(souffle::clone(lit));
                         }
                     } else {
                         res->addToBody(souffle::clone(lit));
                     }
                 }
                 program.removeClause(cl);
                 program.addClause(std::move(res));
                 changed = true;
             }
         }
     }
     return changed;
 }
transform()
bool souffle::RemoveEmptyRelationsTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 47 of file RemoveEmptyRelations.h.
References removeEmptyRelations(), and removeEmptyRelationUses().
{
         return removeEmptyRelations(translationUnit);
     }
The documentation for this class was generated from the following files:
ast/transform/RemoveEmptyRelations.h
ast/transform/RemoveEmptyRelations.cpp