souffle: souffle::SumTypeBranchesAnalysis Class Reference
souffle::SumTypeBranchesAnalysis Class Reference
#include <SumTypeBranches.h>
Public Member Functions
const Type * getType (const std::string &branch) const
A type can be nullptr in case of a malformed program.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
SumTypeBranchesAnalysis ()
const Type & unsafeGetType (const std::string &branch) const
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "sum-type-branches"
Private Attributes
std::map< std::string, const Type * > branchToType
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 25 of file SumTypeBranches.h.
Constructor & Destructor Documentation
SumTypeBranchesAnalysis()
souffle::SumTypeBranchesAnalysis::SumTypeBranchesAnalysis () inline
Definition at line 29 of file SumTypeBranches.h.
References run().
 : AstAnalysis(name) {}
Member Function Documentation
getType()
const Type* souffle::SumTypeBranchesAnalysis::getType (const std::string & branch) const inline
A type can be nullptr in case of a malformed program.
Definition at line 36 of file SumTypeBranches.h.
References branchToType, and souffle::contains().
Referenced by souffle::AstSemanticCheckerImpl::checkBranchInits(), and souffle::TypeConstraintsAnalysis::visitBranchInit().
{
         if (contains(branchToType, branch)) {
             return branchToType.at(branch);
         } else {
             return nullptr;
         }
     }
run()
void souffle::SumTypeBranchesAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 26 of file SumTypeBranches.cpp.
References branchToType, souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::TypeEnvironment::getType(), souffle::AstProgram::getTypes(), souffle::TypeEnvironment::isType(), and souffle::visitDepthFirst().
Referenced by SumTypeBranchesAnalysis().
{
     const TypeEnvironment& env = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
     visitDepthFirst(tu.getProgram()->getTypes(), [&](const AstAlgebraicDataType& adt) {
         auto typeName = adt.getQualifiedName();
         if (!env.isType(typeName)) return;
         for (auto& branch : adt.getBranches()) {
             branchToType[branch->getConstructor()] = &env.getType(typeName);
         }
     });
 }
unsafeGetType()
const Type& souffle::SumTypeBranchesAnalysis::unsafeGetType (const std::string & branch) const inline
Definition at line 44 of file SumTypeBranches.h.
References branchToType.
Referenced by souffle::ADTtoRecordsTransformer::transform().
{
         return *branchToType.at(branch);
     }
Field Documentation
branchToType
std::map<std::string, const Type*> souffle::SumTypeBranchesAnalysis::branchToType private
Definition at line 49 of file SumTypeBranches.h.
Referenced by getType(), run(), and unsafeGetType().
name
constexpr const char* souffle::SumTypeBranchesAnalysis::name = "sum-type-branches" static
Definition at line 27 of file SumTypeBranches.h.
The documentation for this class was generated from the following files:
ast/analysis/SumTypeBranches.h
ast/analysis/SumTypeBranches.cpp