souffle: souffle::ChoiceConversionTransformer Class Reference
souffle::ChoiceConversionTransformer Class Reference
Convert (Scan/If)/(IndexScan/If) operaitons to (Choice)/(IndexChoice) operations.
#include <ChoiceConversion.h>
Public Member Functions
bool convertScans (RamProgram &program)
Apply choice-conversion to the whole program.
std::string getName () const override
get name of the transformer
std::unique_ptr< RamOperation > rewriteIndexScan (const RamIndexScan *indexScan)
Rewrite IndexScan operations.
std::unique_ptr< RamOperation > rewriteScan (const RamScan *scan)
Rewrite Scan operations.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamLevelAnalysis * rla {nullptr}
Detailed Description
Convert (Scan/If)/(IndexScan/If) operaitons to (Choice)/(IndexChoice) operations.
If there exists Scan/IndexScan operations in the RAM, and the variables are used in a subsequent Filter operation but no subsequent operation in the tree (up until and including the Project), the operations are rewritten to Choice/IndexChoice operations.
For example,
QUERY
 ...
  FOR t1 IN A ON INDEX t1.x=10 AND t1.y = 20
   IF (t1.x, t1.y) NOT IN A
        ... // no occurrence of t1
will be rewritten to
QUERY
 ...
  CHOICE A AS t1 ON INDEX t1.x=10 AND t1.y = 20
  WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 62 of file ChoiceConversion.h.
Member Function Documentation
convertScans()
bool souffle::ChoiceConversionTransformer::convertScans (RamProgram & program)
Apply choice-conversion to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for queries and rewrite their Scan/IndexScan and If operations if possible.
Definition at line 114 of file ChoiceConversion.cpp.
References souffle::RamTransformer::apply(), souffle::makeLambdaRamMapper(), rewriteIndexScan(), rewriteScan(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> scanRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamScan* scan = dynamic_cast<RamScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = rewriteScan(scan)) {
                     changed = true;
                     node = std::move(op);
                 }
             } else if (const RamIndexScan* indexScan = dynamic_cast<RamIndexScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = rewriteIndexScan(indexScan)) {
                     changed = true;
                     node = std::move(op);
                 }
             }
             node->apply(makeLambdaRamMapper(scanRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(scanRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ChoiceConversionTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 64 of file ChoiceConversion.h.
References convertScans(), rewriteIndexScan(), and rewriteScan().
{
         return "ChoiceConversionTransformer";
     }
rewriteIndexScan()
std::unique_ptr< RamOperation > souffle::ChoiceConversionTransformer::rewriteIndexScan (const RamIndexScan * indexScan)
Rewrite IndexScan operations.
Parameters
An index operation
Returns
The old operation if the if-conversion fails; otherwise the IndexChoice operation
Rewrites IndexScan/If pair to an IndexChoice operation if value is not used in a consecutive RAM operation
Definition at line 65 of file ChoiceConversion.cpp.
References souffle::RamExpression::clone(), souffle::clone(), souffle::filter(), souffle::RamLevelAnalysis::getLevel(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::RamTupleElement::getTupleId(), souffle::identifier(), rla, and souffle::visitDepthFirst().
Referenced by convertScans(), and getName().
{
     bool transformTuple = false;
     // Check that RamFilter follows the IndexScan in the loop nest
     if (const auto* filter = dynamic_cast<const RamFilter*>(&indexScan->getOperation())) {
         // Check that the Filter uses the identifier in the IndexScan
         if (rla->getLevel(&filter->getCondition()) == indexScan->getTupleId()) {
             transformTuple = true;
             // Check that the filter is not referred to after
             const auto* nextNode = dynamic_cast<const RamNode*>(&filter->getOperation());
             visitDepthFirst(*nextNode, [&](const RamTupleElement& element) {
                 if (element.getTupleId() == indexScan->getTupleId()) {
                     transformTuple = false;
                 }
             });
         }
     }
     // Convert the IndexScan/If pair into an IndexChoice
     if (transformTuple) {
         RamPattern newValues;
         const auto* filter = dynamic_cast<const RamFilter*>(&indexScan->getOperation());
         const int identifier = indexScan->getTupleId();
         const RamRelation& rel = indexScan->getRelation();
         for (auto& cur : indexScan->getRangePattern().first) {
             RamExpression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.first.emplace_back(val);
         }
         for (auto& cur : indexScan->getRangePattern().second) {
             RamExpression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.second.emplace_back(val);
         }
         return std::make_unique<RamIndexChoice>(std::make_unique<RamRelationReference>(&rel), identifier,
                 souffle::clone(&filter->getCondition()), std::move(newValues),
                 souffle::clone(&filter->getOperation()), indexScan->getProfileText());
     }
     return nullptr;
 }
rewriteScan()
std::unique_ptr< RamOperation > souffle::ChoiceConversionTransformer::rewriteScan (const RamScan * scan)
Rewrite Scan operations.
Parameters
A scan operation
Returns
The old operation if the if-conversion fails; otherwise the Choice operation
Rewrites Scan/If pair to a Choice operation if value is not used in a consecutive RAM operation
Definition at line 32 of file ChoiceConversion.cpp.
References souffle::clone(), souffle::filter(), souffle::RamLevelAnalysis::getLevel(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::RamTupleElement::getTupleId(), souffle::identifier(), rla, and souffle::visitDepthFirst().
Referenced by convertScans(), and getName().
{
     bool transformTuple = false;
     // Check that RamFilter follows the Scan in the loop nest
     if (const auto* filter = dynamic_cast<const RamFilter*>(&scan->getOperation())) {
         // Check that the Filter uses the identifier in the Scan
         if (rla->getLevel(&filter->getCondition()) == scan->getTupleId()) {
             transformTuple = true;
             // Check that the filter is not referred to after
             const auto* nextNode = dynamic_cast<const RamNode*>(&filter->getOperation());
             visitDepthFirst(*nextNode, [&](const RamTupleElement& element) {
                 if (element.getTupleId() == scan->getTupleId()) {
                     transformTuple = false;
                 }
             });
         }
     }
     // Convert the Scan/If pair into a Choice
     if (transformTuple) {
         std::vector<std::unique_ptr<RamExpression>> newValues;
         const auto* filter = dynamic_cast<const RamFilter*>(&scan->getOperation());
         const int identifier = scan->getTupleId();
         return std::make_unique<RamChoice>(std::make_unique<RamRelationReference>(&scan->getRelation()),
                 identifier, souffle::clone(&filter->getCondition()), souffle::clone(&scan->getOperation()),
                 scan->getProfileText());
     }
     return nullptr;
 }
transform()
bool souffle::ChoiceConversionTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 99 of file ChoiceConversion.h.
References convertScans(), souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), and rla.
{
         rla = translationUnit.getAnalysis<RamLevelAnalysis>();
         return convertScans(translationUnit.getProgram());
     }
Field Documentation
rla
RamLevelAnalysis* souffle::ChoiceConversionTransformer::rla {nullptr} protected
Definition at line 98 of file ChoiceConversion.h.
Referenced by rewriteIndexScan(), rewriteScan(), and transform().
The documentation for this class was generated from the following files:
ram/transform/ChoiceConversion.h
ram/transform/ChoiceConversion.cpp