souffle: souffle::AddNullariesToAtomlessAggregatesTransformer Class Reference
souffle::AddNullariesToAtomlessAggregatesTransformer Class Reference
Transformation pass to add artificial nullary atom (+Tautology()) to aggregate bodies that have no atoms.
#include <AddNullariesToAtomlessAggregates.h>
Public Member Functions
AddNullariesToAtomlessAggregatesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to add artificial nullary atom (+Tautology()) to aggregate bodies that have no atoms.
Definition at line 35 of file AddNullariesToAtomlessAggregates.h.
Member Function Documentation
clone()
AddNullariesToAtomlessAggregatesTransformer* souffle::AddNullariesToAtomlessAggregatesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 41 of file AddNullariesToAtomlessAggregates.h.
References transform().
{
         return new AddNullariesToAtomlessAggregatesTransformer();
     }
getName()
std::string souffle::AddNullariesToAtomlessAggregatesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 37 of file AddNullariesToAtomlessAggregates.h.
{
         return "AddNullariesToAtomlessAggregatesTransformer";
     }
transform()
bool souffle::AddNullariesToAtomlessAggregatesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 33 of file AddNullariesToAtomlessAggregates.cpp.
References souffle::AstProgram::addClause(), souffle::AstProgram::addRelation(), souffle::clone(), souffle::AstAggregator::getBodyLiterals(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), and souffle::visitDepthFirst().
Referenced by clone().
{
     bool changed{false};
     AstProgram& program = *translationUnit.getProgram();
     visitDepthFirst(program, [&](const AstAggregator& agg) {
         bool seenAtom{false};
         for (const auto& literal : agg.getBodyLiterals()) {
             if (dynamic_cast<const AstAtom*>(literal) != nullptr) {
                 seenAtom = true;
             }
         }
         if (seenAtom) {
             return;
         }
         // We will add in the Tautology atom to the body of this aggregate now
         changed = true;
         // +Tautology()
         auto nullaryAtom = std::make_unique<AstAtom>();
         std::string relName = "+Tautology";
         nullaryAtom->setQualifiedName(relName);
         if (getRelation(program, relName) == nullptr) {
             // +Tautology().
             auto fact = std::make_unique<AstClause>();
             fact->setHead(souffle::clone(nullaryAtom));
             // .decl +Tautology()
             auto tautologyRel = std::make_unique<AstRelation>();
             tautologyRel->setQualifiedName(relName);
             program.addRelation(std::move(tautologyRel));
             program.addClause(std::move(fact));
         }
         VecOwn<AstLiteral> newBody;
         for (const auto& lit : agg.getBodyLiterals()) {
             newBody.push_back(souffle::clone(lit));
         }
         newBody.push_back(souffle::clone(nullaryAtom));
         const_cast<AstAggregator&>(agg).setBody(std::move(newBody));
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/AddNullariesToAtomlessAggregates.h
ast/transform/AddNullariesToAtomlessAggregates.cpp