souffle: souffle::AstAlgebraicDataType Class Reference
souffle::AstAlgebraicDataType Class Reference
Combination of types using sums and products.
#include <AlgebraicDataType.h>
Public Member Functions
AstAlgebraicDataType (AstQualifiedName name, VecOwn< AstBranchDeclaration > branches, SrcLocation loc={})
AstAlgebraicDataType * clone () const override
Create a clone (i.e.
std::vector< AstBranchDeclaration * > getBranches () const
void print (std::ostream &os) const override
Output to a given output stream.
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={}, SrcLocation loc={})
const AstQualifiedName & getQualifiedName () const
Return type name.
void setQualifiedName (AstQualifiedName name)
Set type name.
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Private Attributes
VecOwn< AstBranchDeclaration > branches
The list of branches for this sum type.
Detailed Description
Combination of types using sums and products.
ADT combines a simpler types using product types and sum types.
Example: .type Nat = S {n : Nat} | Zero {}
The type Nat has two branches, S which takes element of type Nat and Zero which doesn't take any arguments.
Definition at line 39 of file AlgebraicDataType.h.
Constructor & Destructor Documentation
AstAlgebraicDataType()
souffle::AstAlgebraicDataType::AstAlgebraicDataType (AstQualifiedName name, VecOwn< AstBranchDeclaration > branches, SrcLocation loc = {}) inline
Definition at line 41 of file AlgebraicDataType.h.
References souffle::AstType::AstType(), and branches.
Referenced by clone().
                                                                                                          {})
             : AstType(std::move(name), std::move(loc)), branches(std::move(branches)) {
         assert(!this->branches.empty());
     };
Member Function Documentation
clone()
AstAlgebraicDataType* souffle::AstAlgebraicDataType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 54 of file AlgebraicDataType.h.
References AstAlgebraicDataType(), souffle::clone(), souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         return new AstAlgebraicDataType(getQualifiedName(), souffle::clone(branches), getSrcLoc());
     }
equal()
bool souffle::AstAlgebraicDataType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 59 of file AlgebraicDataType.h.
References souffle::AstType::getQualifiedName().
{
         const auto& other = dynamic_cast<const AstAlgebraicDataType&>(node);
         return getQualifiedName() == other.getQualifiedName() && branches == other.branches;
     }
getBranches()
std::vector<AstBranchDeclaration*> souffle::AstAlgebraicDataType::getBranches () const inline
Definition at line 46 of file AlgebraicDataType.h.
References souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkADT().
{
         return toPtrVector(branches);
     }
print()
void souffle::AstAlgebraicDataType::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 50 of file AlgebraicDataType.h.
References tinyformat::format(), souffle::AstType::getQualifiedName(), and souffle::join().
{
         os << tfm::format(".type %s = %s", getQualifiedName(), join(branches, " | "));
     }
Field Documentation
branches
VecOwn<AstBranchDeclaration> souffle::AstAlgebraicDataType::branches private
The list of branches for this sum type.
Definition at line 66 of file AlgebraicDataType.h.
Referenced by AstAlgebraicDataType().
The documentation for this class was generated from the following file:
ast/AlgebraicDataType.h