souffle: souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore Class Reference
souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore Class Reference
A storage of bound variables that dynamically determines the set of bound variables within a clause.
#include <MagicSet.h>
Public Member Functions
BindingStore (const AstClause *clause, const std::string &adornmentMarker)
void bindVariable (std::string varName)
bool isBound (std::string varName) const
Private Types
using ConjBindingSet = std::set< std::string >
using DisjBindingSet = std::set< ConjBindingSet >
Private Member Functions
void addBindingDependency (std::string variable, ConjBindingSet dependency)
Add a new conjunction of variables as a potential binder for a given variable.
void generateBindingDependencies (const AstClause *clause)
Generate all binding dependencies implied by the constraints within a given clause.
void processEqualityBindings (const AstArgument *lhs, const AstArgument *rhs)
Add binding dependencies formed on lhs by a <lhs> = <rhs> equality constraint.
bool reduceDependencies ()
Reduce the full set of dependencies for all tracked variables, binding whatever needs to be bound.
ConjBindingSet reduceDependency (const ConjBindingSet &origDependency)
Reduce a conjunctive set of dependencies based on the current bound variable set.
DisjBindingSet reduceDependency (const DisjBindingSet &origDependency)
Reduce a disjunctive set of variable dependencies based on the current bound variable set.
Private Attributes
std::set< std::string > boundHeadVariables {}
std::set< std::string > boundVariables {}
std::map< std::string, DisjBindingSet > variableDependencies {}
Detailed Description
A storage of bound variables that dynamically determines the set of bound variables within a clause.
Definition at line 318 of file MagicSet.h.
Member Typedef Documentation
ConjBindingSet
using souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::ConjBindingSet = std::set<std::string> private
Definition at line 333 of file MagicSet.h.
DisjBindingSet
using souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::DisjBindingSet = std::set<ConjBindingSet> private
Definition at line 334 of file MagicSet.h.
Constructor & Destructor Documentation
BindingStore()
souffle::BindingStore::BindingStore (const AstClause * clause, const std::string & adornmentMarker)
Definition at line 1093 of file MagicSet.cpp.
References souffle::EQ, souffle::AstAtom::getArguments(), souffle::AstClause::getHead(), souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), i, and souffle::visitDepthFirst().
{
     /* Note that variables can be bound through:
      *  (1) an appearance in a body atom
      *  (2) an appearance in a bound field of the head atom
      *  (3) equality with a fully bound functor (via this class)
      *
      * When computing (3), appearances (1) and (2) must be separated to maintain the termination semantics of
      * the original program. Functor variables are not considered bound if they are only bound via the head.
      *
      * Justification: Suppose a new variable Y is marked as bound because of its appearance in a functor
      * Y=X+1, and X was already found to be bound:
      *  (1) If X was bound through a body atom, then the behaviour of typical magic-set is exhibited, where
      * the magic-set of Y is bounded by the values that X can take, which is bounded by induction.
      *  (2) If X was bound only through the head atom, then Y is only fixed to an appearance in a magic-atom.
      * In the presence of recursion, this can potentially lead to an infinitely-sized magic-set for an atom.
      */
     // Bind variables in the head that are marked as bound args
     const auto& headArgs = clause->getHead()->getArguments();
     for (size_t i = 0; i < adornmentMarker.length(); i++) {
         const auto* var = dynamic_cast<AstVariable*>(headArgs[i]);
         assert(var != nullptr && "expected only variables in head");
         if (adornmentMarker[i] == 'b') {
             boundHeadVariables.insert(var->getName());
         }
     }
     // Check through for variables bound in the body by a '<var> = <const>' term
     visitDepthFirst(*clause, [&](const AstBinaryConstraint& constr) {
         if (constr.getOperator() == BinaryConstraintOp::EQ && dynamic_cast<AstVariable*>(constr.getLHS()) &&
                 dynamic_cast<AstConstant*>(constr.getRHS())) {
             const auto* var = dynamic_cast<AstVariable*>(constr.getLHS());
             bindVariable(var->getName());
         }
     });
     generateBindingDependencies(clause);
     reduceDependencies();
 }
Member Function Documentation
addBindingDependency()
void souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::addBindingDependency (std::string variable, ConjBindingSet dependency) inline private
Add a new conjunction of variables as a potential binder for a given variable.
The variable is considered bound if all variables in the conjunction are bound.
Definition at line 344 of file MagicSet.h.
References souffle::contains(), lhs, and rhs.
{
         if (!contains(variableDependencies, variable)) {
             variableDependencies[variable] = DisjBindingSet();
         }
         variableDependencies[variable].insert(dependency);
     }
bindVariable()
void souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::bindVariable (std::string varName) inline
Definition at line 322 of file MagicSet.h.
Referenced by souffle::MagicSetTransformer::AdornDatabaseTransformer::adornClause().
{
         boundVariables.insert(varName);
         reduceDependencies();
     }
generateBindingDependencies()
void souffle::BindingStore::generateBindingDependencies (const AstClause * clause) private
Generate all binding dependencies implied by the constraints within a given clause.
Definition at line 1153 of file MagicSet.cpp.
References souffle::EQ, souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), and souffle::visitDepthFirst().
{
     // Grab all relevant constraints (i.e. eq. constrs not involving aggregators)
     std::set<const AstBinaryConstraint*> constraints;
     visitDepthFirst(*clause, [&](const AstBinaryConstraint& bc) {
         bool containsAggregators = false;
         visitDepthFirst(bc, [&](const AstAggregator& /* aggr */) { containsAggregators = true; });
         if (!containsAggregators && bc.getOperator() == BinaryConstraintOp::EQ) {
             constraints.insert(&bc);
         }
     });
     // Add variable binding dependencies implied by the constraint
     for (const auto* bc : constraints) {
         processEqualityBindings(bc->getLHS(), bc->getRHS());
         processEqualityBindings(bc->getRHS(), bc->getLHS());
     }
 }
isBound()
bool souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::isBound (std::string varName) const inline
Definition at line 327 of file MagicSet.h.
References souffle::contains().
Referenced by souffle::MagicSetTransformer::AdornDatabaseTransformer::adornClause().
{
         return contains(boundVariables, varName) || contains(boundHeadVariables, varName);
     }
processEqualityBindings()
void souffle::BindingStore::processEqualityBindings (const AstArgument * lhs, const AstArgument * rhs) private
Add binding dependencies formed on lhs by a <lhs> = <rhs> equality constraint.
Definition at line 1133 of file MagicSet.cpp.
References souffle::AstVariable::getName(), lhs, and souffle::visitDepthFirst().
{
     // Only care about equalities affecting the bound status of variables
     const auto* var = dynamic_cast<const AstVariable*>(lhs);
     if (var == nullptr) return;
     // If all variables on the rhs are bound, then lhs is also bound
     BindingStore::ConjBindingSet depSet;
     visitDepthFirst(*rhs, [&](const AstVariable& subVar) { depSet.insert(subVar.getName()); });
     addBindingDependency(var->getName(), depSet);
     // If the lhs is bound, then all args in the rec on the rhs are also bound
     if (const auto* rec = dynamic_cast<const AstRecordInit*>(rhs)) {
         for (const auto* arg : rec->getArguments()) {
             const auto* subVar = dynamic_cast<const AstVariable*>(arg);
             assert(subVar != nullptr && "expected args to be variables");
             addBindingDependency(subVar->getName(), BindingStore::ConjBindingSet({var->getName()}));
         }
     }
 }
reduceDependencies()
bool souffle::BindingStore::reduceDependencies () private
Reduce the full set of dependencies for all tracked variables, binding whatever needs to be bound.
Definition at line 1195 of file MagicSet.cpp.
References souffle::contains().
{
     bool changed = false;
     std::map<std::string, BindingStore::DisjBindingSet> newVariableDependencies;
     std::set<std::string> variablesToBind;
     // Reduce each variable's set of dependencies one by one
     for (const auto& [headVar, dependencies] : variableDependencies) {
         // No need to track the dependencies of already-bound variables
         if (contains(boundVariables, headVar)) {
             changed = true;
             continue;
         }
         // Reduce the dependency set based on bound variables
         auto newDependencies = reduceDependency(dependencies);
         if (newDependencies.empty() || newDependencies.size() < dependencies.size()) {
             // At least one dependency has been satisfied, so variable is now bound
             changed = true;
             variablesToBind.insert(headVar);
             continue;
         }
         newVariableDependencies[headVar] = newDependencies;
         changed |= (newDependencies != dependencies);
     }
     // Bind variables that need to be bound
     for (auto var : variablesToBind) {
         boundVariables.insert(var);
     }
     // Repeat it recursively if any changes happened, until we reach a fixpoint
     if (changed) {
         variableDependencies = newVariableDependencies;
         reduceDependencies();
         return true;
     }
     assert(variableDependencies == newVariableDependencies && "unexpected change");
     return false;
 }
reduceDependency() [1/2]
BindingStore::ConjBindingSet souffle::BindingStore::reduceDependency (const ConjBindingSet & origDependency) private
Reduce a conjunctive set of dependencies based on the current bound variable set.
Definition at line 1171 of file MagicSet.cpp.
References souffle::contains().
{
     BindingStore::ConjBindingSet newDependency;
     for (const auto& var : origDependency) {
         // Only keep unbound variables in the dependency
         if (!contains(boundVariables, var)) {
             newDependency.insert(var);
         }
     }
     return newDependency;
 }
reduceDependency() [2/2]
BindingStore::DisjBindingSet souffle::BindingStore::reduceDependency (const DisjBindingSet & origDependency) private
Reduce a disjunctive set of variable dependencies based on the current bound variable set.
Definition at line 1183 of file MagicSet.cpp.
{
     BindingStore::DisjBindingSet newDependencies;
     for (const auto& dep : origDependency) {
         auto newDep = reduceDependency(dep);
         if (!newDep.empty()) {
             newDependencies.insert(newDep);
         }
     }
     return newDependencies;
 }
Field Documentation
boundHeadVariables
std::set<std::string> souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::boundHeadVariables {} private
Definition at line 337 of file MagicSet.h.
boundVariables
std::set<std::string> souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::boundVariables {} private
Definition at line 336 of file MagicSet.h.
variableDependencies
std::map<std::string, DisjBindingSet> souffle::MagicSetTransformer::AdornDatabaseTransformer::BindingStore::variableDependencies {} private
Definition at line 338 of file MagicSet.h.
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp