souffle: souffle::RamParallelIndexAggregate Class Reference
souffle::RamParallelIndexAggregate Class Reference
Aggregate over values of a relation using an index in parallel.
#include <ParallelIndexAggregate.h>
Public Member Functions
RamParallelIndexAggregate * clone () const override
Create a clone (i.e.
RamParallelIndexAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, RamPattern queryPattern, int ident)
Public Member Functions inherited from souffle::RamIndexAggregate
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamIndexAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, RamPattern queryPattern, int ident)
Public Member Functions inherited from souffle::RamIndexOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::pair< std::vector< RamExpression * >, std::vector< RamExpression * > > getRangePattern () const
Get range pattern.
void printIndex (std::ostream &os) const
Helper method for printing.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractAggregate
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Get condition.
const RamExpression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
RamAbstractAggregate (AggregateOp fun, std::unique_ptr< RamExpression > expr, std::unique_ptr< RamCondition > cond)
virtual ~RamAbstractAggregate ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamIndexAggregate
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamIndexOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamRelationOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamTupleOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::RamAbstractAggregate
bool equal (const RamNode &node) const
void print (std::ostream &os, int) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamIndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractAggregate
std::unique_ptr< RamCondition > condition
Aggregation tuple condition.
std::unique_ptr< RamExpression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Aggregate over values of a relation using an index in parallel.
For example:
t0.0=sum t0.1 SEARCH t0  S ON INDEX t0.0 = number(1)
Definition at line 48 of file ParallelIndexAggregate.h.
Constructor & Destructor Documentation
RamParallelIndexAggregate()
souffle::RamParallelIndexAggregate::RamParallelIndexAggregate (std::unique_ptr< RamOperation > nested, AggregateOp fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, RamPattern queryPattern, int ident) inline
Definition at line 50 of file ParallelIndexAggregate.h.
Referenced by clone().
             : RamIndexAggregate(std::move(nested), fun, std::move(relRef), std::move(expression),
                       std::move(condition), std::move(queryPattern), ident) {}
Member Function Documentation
clone()
RamParallelIndexAggregate* souffle::RamParallelIndexAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamIndexAggregate.
Definition at line 56 of file ParallelIndexAggregate.h.
References souffle::clone(), souffle::RamAbstractAggregate::condition, souffle::RamAbstractAggregate::expression, souffle::RamNestedOperation::getOperation(), souffle::RamTupleOperation::getTupleId(), i, souffle::RamIndexOperation::queryPattern, RamParallelIndexAggregate(), and souffle::RamRelationOperation::relationRef.
{
         RamPattern pattern;
         for (const auto& i : queryPattern.first) {
             pattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             pattern.second.emplace_back(i->clone());
         }
         return new RamParallelIndexAggregate(souffle::clone(&getOperation()), function,
                 souffle::clone(relationRef), souffle::clone(expression), souffle::clone(condition),
                 std::move(pattern), getTupleId());
     }
print()
void souffle::RamParallelIndexAggregate::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamIndexAggregate.
Definition at line 70 of file ParallelIndexAggregate.h.
References souffle::RamAbstractAggregate::condition, souffle::RamAbstractAggregate::getCondition(), souffle::RamRelation::getName(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::isRamTrue(), souffle::RamAbstractAggregate::print(), souffle::RamNestedOperation::print(), souffle::RamIndexOperation::printIndex(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL t" << getTupleId() << ".0=";
         RamAbstractAggregate::print(os, tabpos);
         os << "SEARCH t" << getTupleId() << "  " << getRelation().getName();
         printIndex(os);
         if (!isRamTrue(condition.get())) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         RamIndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/ParallelIndexAggregate.h