souffle: souffle::AstBranchInit Class Reference
souffle::AstBranchInit Class Reference
Initialization of ADT instance.
#include <BranchInit.h>
Public Member Functions
AstBranchInit (std::string constructor, VecOwn< AstArgument > args, SrcLocation loc={})
AstBranchInit * clone () const override
Create clone.
const std::string & getConstructor () const
Public Member Functions inherited from souffle::AstTerm
void addArgument (Own< AstArgument > arg)
Add argument to argument list.
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
Get arguments.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstTerm
template<typename... Operands>
AstTerm (Operands &&... operands)
template<typename... Operands>
AstTerm (SrcLocation loc, Operands &&... operands)
AstTerm (VecOwn< AstArgument > operands, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Private Attributes
std::string constructor
The adt branch constructor.
Additional Inherited Members
Protected Attributes inherited from souffle::AstTerm
VecOwn< AstArgument > args
Arguments.
Detailed Description
Initialization of ADT instance.
Parameters
constructor An entity used to create a variant type. Can be though of as a name of the branch.
Initializes one of the branches of ADT. The syntax for branches initialization is $Constructor(args...) In case of the branch with no arguments it is simplified to $Constructor.
Definition at line 42 of file BranchInit.h.
Constructor & Destructor Documentation
AstBranchInit()
souffle::AstBranchInit::AstBranchInit (std::string constructor, VecOwn< AstArgument > args, SrcLocation loc = {}) inline
Definition at line 44 of file BranchInit.h.
References souffle::AstTerm::AstTerm(), and constructor.
Referenced by clone().
                                                                                      {})
             : AstTerm(std::move(args), std::move(loc)), constructor(std::move(constructor)) {}
Member Function Documentation
clone()
AstBranchInit* souffle::AstBranchInit::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 51 of file BranchInit.h.
References AstBranchInit(), souffle::clone(), and souffle::AstNode::getSrcLoc().
{
         return new AstBranchInit(constructor, souffle::clone(args), getSrcLoc());
     }
equal()
bool souffle::AstBranchInit::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Reimplemented from souffle::AstNode.
Definition at line 61 of file BranchInit.h.
References souffle::equal_targets().
{
         const auto& other = dynamic_cast<const AstBranchInit&>(node);
         return (constructor == other.constructor) && equal_targets(args, other.args);
     }
getConstructor()
const std::string& souffle::AstBranchInit::getConstructor () const inline
Definition at line 47 of file BranchInit.h.
References constructor.
Referenced by souffle::TypeChecker::visitBranchInit(), and souffle::TypeConstraintsAnalysis::visitBranchInit().
{
         return constructor;
     }
print()
void souffle::AstBranchInit::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 56 of file BranchInit.h.
References tinyformat::format(), and souffle::join().
{
         os << tfm::format("$%s(%s)", constructor, join(args, ", "));
     }
Field Documentation
constructor
std::string souffle::AstBranchInit::constructor private
The adt branch constructor.
Definition at line 68 of file BranchInit.h.
Referenced by AstBranchInit(), and getConstructor().
The documentation for this class was generated from the following file:
ast/BranchInit.h