souffle: souffle::MagicSetTransformer::NormaliseDatabaseTransformer Class Reference
souffle::MagicSetTransformer::NormaliseDatabaseTransformer Class Reference
Database normaliser for MST.
#include <MagicSet.h>
Public Member Functions
NormaliseDatabaseTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static bool extractIDB (AstTranslationUnit &translationUnit)
Separates the IDB from the EDB, so that they are disjoint.
static bool normaliseArguments (AstTranslationUnit &translationUnit)
Normalise all arguments within each clause.
static bool partitionIO (AstTranslationUnit &translationUnit)
Partitions the input and output relations.
static bool querifyOutputRelations (AstTranslationUnit &translationUnit)
Extracts output relations into separate simple query relations, so that they are unused in any other rules.
Detailed Description
Database normaliser for MST.
Effects:
Partitions database into [input|intermediate|queries]
Normalises all arguments and constraints Prerequisite for adornment.
Definition at line 97 of file MagicSet.h.
Member Function Documentation
clone()
NormaliseDatabaseTransformer* souffle::MagicSetTransformer::NormaliseDatabaseTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 103 of file MagicSet.h.
References souffle::MagicSetTransformer::transform().
{
         return new NormaliseDatabaseTransformer();
     }
extractIDB()
bool souffle::NormaliseDatabaseTransformer::extractIDB (AstTranslationUnit & translationUnit) static private
Separates the IDB from the EDB, so that they are disjoint.
Program will no longer have input relations that appear as the head of clauses.
Definition at line 268 of file MagicSet.cpp.
References souffle::clone(), souffle::AstTranslationUnit::getAnalysis(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), i, souffle::AstQualifiedName::prepend(), souffle::renameAtoms(), and souffle::visitDepthFirst().
Referenced by transform().
{
     auto& program = *translationUnit.getProgram();
     const auto& ioTypes = *translationUnit.getAnalysis<IOType>();
     // Helper method to check if an input relation has no associated rules
     auto isStrictlyEDB = [&](const AstRelation* rel) {
         bool hasRules = false;
         for (const auto* clause : getClauses(program, rel->getQualifiedName())) {
             visitDepthFirst(clause->getBodyLiterals(), [&](const AstAtom& /* atom */) { hasRules = true; });
         }
         return !hasRules;
     };
     // Get all input relations that also have IDB rules attached
     std::set<AstQualifiedName> inputRelationNames;
     for (auto* rel : program.getRelations()) {
         if (ioTypes.isInput(rel) && !isStrictlyEDB(rel)) {
             assert(!ioTypes.isOutput(rel) && !ioTypes.isPrintSize(rel) &&
                     "input relations should not be output at this stage");
             inputRelationNames.insert(rel->getQualifiedName());
         }
     }
     // Add a new intermediate non-input relation for each
     // These will cover relation appearances in IDB rules
     std::map<AstQualifiedName, AstQualifiedName> inputToIntermediate;
     for (const auto& inputRelationName : inputRelationNames) {
         // Give it a unique name
         AstQualifiedName intermediateName(inputRelationName);
         intermediateName.prepend("@interm_in");
         inputToIntermediate[inputRelationName] = intermediateName;
         // Add the relation
         auto intermediateRelation = souffle::clone(getRelation(program, inputRelationName));
         intermediateRelation->setQualifiedName(intermediateName);
         program.addRelation(std::move(intermediateRelation));
     }
     // Rename them systematically
     renameAtoms(program, inputToIntermediate);
     // Add the rule I' <- I
     for (const auto& inputRelationName : inputRelationNames) {
         auto queryHead = std::make_unique<AstAtom>(inputToIntermediate.at(inputRelationName));
         auto queryLiteral = std::make_unique<AstAtom>(inputRelationName);
         // Give them identical arguments
         const auto* inputRelation = getRelation(program, inputRelationName);
         for (size_t i = 0; i < inputRelation->getArity(); i++) {
             std::stringstream var;
             var << "@query_x" << i;
             queryHead->addArgument(std::make_unique<AstVariable>(var.str()));
             queryLiteral->addArgument(std::make_unique<AstVariable>(var.str()));
         }
         auto query = std::make_unique<AstClause>(std::move(queryHead));
         query->addToBody(std::move(queryLiteral));
         program.addClause(std::move(query));
     }
     return !inputRelationNames.empty();
 }
getName()
std::string souffle::MagicSetTransformer::NormaliseDatabaseTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 99 of file MagicSet.h.
{
         return "NormaliseDatabaseTransformer";
     }
normaliseArguments()
bool souffle::NormaliseDatabaseTransformer::normaliseArguments (AstTranslationUnit & translationUnit) static private
Normalise all arguments within each clause.
All arguments in all clauses will now be either: (1) a variable, or (2) the RHS of a <var> = <arg> constraint
Definition at line 405 of file MagicSet.cpp.
References souffle::clone(), souffle::EQ, souffle::AstTerm::getArguments(), souffle::AstTranslationUnit::getProgram(), and souffle::visitDepthFirst().
Referenced by transform().
{
     auto& program = *translationUnit.getProgram();
     // Replace all non-variable-arguments nested inside the node with named variables
     // Also, keeps track of constraints to add to keep the clause semantically equivalent
     struct argument_normaliser : public AstNodeMapper {
         std::set<std::unique_ptr<AstBinaryConstraint>>& constraints;
         int& changeCount;
         argument_normaliser(std::set<std::unique_ptr<AstBinaryConstraint>>& constraints, int& changeCount)
                 : constraints(constraints), changeCount(changeCount) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* aggr = dynamic_cast<AstAggregator*>(node.get())) {
                 // Aggregator variable scopes should be maintained, so changes shouldn't propagate
                 // above this level.
                 std::set<std::unique_ptr<AstBinaryConstraint>> subConstraints;
                 argument_normaliser aggrUpdate(subConstraints, changeCount);
                 aggr->apply(aggrUpdate);
                 // Add the constraints to this level
                 std::vector<std::unique_ptr<AstLiteral>> newBodyLiterals;
                 for (const auto* lit : aggr->getBodyLiterals()) {
                     newBodyLiterals.push_back(souffle::clone(lit));
                 }
                 for (auto& constr : subConstraints) {
                     newBodyLiterals.push_back(souffle::clone(constr));
                 }
                 // Update the node to reflect normalised aggregator
                 node = aggr->getTargetExpression() != nullptr
                                ? std::make_unique<AstAggregator>(aggr->getOperator(),
                                          souffle::clone(aggr->getTargetExpression()),
                                          std::move(newBodyLiterals))
                                : std::make_unique<AstAggregator>(
                                          aggr->getOperator(), nullptr, std::move(newBodyLiterals));
             } else {
                 // Otherwise, just normalise children as usual.
                 node->apply(*this);
             }
             // All non-variables should be normalised
             if (auto* arg = dynamic_cast<AstArgument*>(node.get())) {
                 if (dynamic_cast<AstVariable*>(arg) == nullptr) {
                     std::stringstream name;
                     name << "@abdul" << changeCount++;
                     // Unnamed variables don't need a new constraint, just give them a name
                     if (dynamic_cast<AstUnnamedVariable*>(arg) != nullptr) {
                         return std::make_unique<AstVariable>(name.str());
                     }
                     // Link other variables back to their original value with a `<var> = <arg>` constraint
                     constraints.insert(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                             std::make_unique<AstVariable>(name.str()), souffle::clone(arg)));
                     return std::make_unique<AstVariable>(name.str());
                 }
             }
             return node;
         }
     };
     // Transform each clause so that all arguments are:
     //      1) a variable, or
     //      2) the RHS of a `<var> = <arg>` constraint
     bool changed = false;
     for (auto* clause : program.getClauses()) {
         int changeCount = 0;
         std::set<std::unique_ptr<AstBinaryConstraint>> constraintsToAdd;
         argument_normaliser update(constraintsToAdd, changeCount);
         // Apply to each clause head
         clause->getHead()->apply(update);
         // Apply to each body literal that isn't already a `<var> = <arg>` constraint
         for (AstLiteral* lit : clause->getBodyLiterals()) {
             if (auto* bc = dynamic_cast<AstBinaryConstraint*>(lit)) {
                 if (bc->getOperator() == BinaryConstraintOp::EQ &&
                         dynamic_cast<AstVariable*>(bc->getLHS()) != nullptr) {
                     continue;
                 }
             }
             lit->apply(update);
         }
         // Also apply to each record
         visitDepthFirst(*clause, [&](const AstRecordInit& rec) {
             for (AstArgument* arg : rec.getArguments()) {
                 arg->apply(update);
             }
         });
         // Add each necessary new constraint to the clause
         for (auto& constraint : constraintsToAdd) {
             clause->addToBody(souffle::clone(constraint));
         }
         changed |= changeCount != 0;
     }
     return changed;
 }
partitionIO()
bool souffle::NormaliseDatabaseTransformer::partitionIO (AstTranslationUnit & translationUnit) static private
Partitions the input and output relations.
Program will no longer have relations that are both input and output.
Definition at line 200 of file MagicSet.cpp.
References souffle::clone(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), i, and souffle::input.
Referenced by transform().
{
     auto& program = *translationUnit.getProgram();
     const auto& ioTypes = *translationUnit.getAnalysis<IOType>();
     // Get all relations that are both input and output
     std::set<AstQualifiedName> relationsToSplit;
     for (auto* rel : program.getRelations()) {
         if (ioTypes.isInput(rel) && (ioTypes.isOutput(rel) || ioTypes.isPrintSize(rel))) {
             relationsToSplit.insert(rel->getQualifiedName());
         }
     }
     // For each of these relations I, add a new relation I' that's input instead.
     // The old relation I is no longer input, but copies over the data from I'.
     for (auto relName : relationsToSplit) {
         const auto* rel = getRelation(program, relName);
         assert(rel != nullptr && "relation does not exist");
         auto newRelName = AstQualifiedName(relName);
         newRelName.prepend("@split_in");
         // Create a new intermediate input relation, I'
         auto newRelation = std::make_unique<AstRelation>(newRelName);
         for (const auto* attr : rel->getAttributes()) {
             newRelation->addAttribute(souffle::clone(attr));
         }
         // Add the rule I <- I'
         auto newClause = std::make_unique<AstClause>();
         auto newHeadAtom = std::make_unique<AstAtom>(relName);
         auto newBodyAtom = std::make_unique<AstAtom>(newRelName);
         for (size_t i = 0; i < rel->getArity(); i++) {
             std::stringstream varName;
             varName << "@var" << i;
             newHeadAtom->addArgument(std::make_unique<AstVariable>(varName.str()));
             newBodyAtom->addArgument(std::make_unique<AstVariable>(varName.str()));
         }
         newClause->setHead(std::move(newHeadAtom));
         newClause->addToBody(std::move(newBodyAtom));
         // New relation I' should be input, original should not
         std::set<const AstIO*> iosToDelete;
         std::set<std::unique_ptr<AstIO>> iosToAdd;
         for (const auto* io : program.getIOs()) {
             if (io->getQualifiedName() == relName && io->getType() == AstIoType::input) {
                 // New relation inherits the old input rules
                 auto newIO = souffle::clone(io);
                 newIO->setQualifiedName(newRelName);
                 iosToAdd.insert(std::move(newIO));
                 // Original no longer has them
                 iosToDelete.insert(io);
             }
         }
         for (const auto* io : iosToDelete) {
             program.removeIO(io);
         }
         for (auto& io : iosToAdd) {
             program.addIO(souffle::clone(io));
         }
         // Add in the new relation and the copy clause
         program.addRelation(std::move(newRelation));
         program.addClause(std::move(newClause));
     }
     return !relationsToSplit.empty();
 }
querifyOutputRelations()
bool souffle::NormaliseDatabaseTransformer::querifyOutputRelations (AstTranslationUnit & translationUnit) static private
Extracts output relations into separate simple query relations, so that they are unused in any other rules.
Programs will only contain output relations which: (1) have exactly one rule defining them (2) do not appear in other rules
Definition at line 331 of file MagicSet.cpp.
References souffle::clone(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), i, souffle::AstQualifiedName::prepend(), souffle::renameAtoms(), and souffle::visitDepthFirst().
Referenced by transform().
{
     auto& program = *translationUnit.getProgram();
     // Helper method to check if a relation is a single-rule output query
     auto isStrictlyOutput = [&](const AstRelation* rel) {
         bool strictlyOutput = true;
         size_t ruleCount = 0;
         for (const auto* clause : program.getClauses()) {
             // Check if the relation is used in the body of any rules
             visitDepthFirst(clause->getBodyLiterals(), [&](const AstAtom& atom) {
                 if (atom.getQualifiedName() == rel->getQualifiedName()) {
                     strictlyOutput = false;
                 }
             });
             // Keep track of number of rules defining the relation
             if (clause->getHead()->getQualifiedName() == rel->getQualifiedName()) {
                 ruleCount++;
             }
         }
         return strictlyOutput && ruleCount <= 1;
     };
     // Get all output relations that need to be normalised
     const auto& ioTypes = *translationUnit.getAnalysis<IOType>();
     std::set<AstQualifiedName> outputRelationNames;
     for (auto* rel : program.getRelations()) {
         if ((ioTypes.isOutput(rel) || ioTypes.isPrintSize(rel)) && !isStrictlyOutput(rel)) {
             assert(!ioTypes.isInput(rel) && "output relations should not be input at this stage");
             outputRelationNames.insert(rel->getQualifiedName());
         }
     }
     // Add a new intermediate non-output relation for each
     // These will cover relation appearances in intermediate rules
     std::map<AstQualifiedName, AstQualifiedName> outputToIntermediate;
     for (const auto& outputRelationName : outputRelationNames) {
         // Give it a unique name
         AstQualifiedName intermediateName(outputRelationName);
         intermediateName.prepend("@interm_out");
         outputToIntermediate[outputRelationName] = intermediateName;
         // Add the relation
         auto intermediateRelation = souffle::clone(getRelation(program, outputRelationName));
         intermediateRelation->setQualifiedName(intermediateName);
         program.addRelation(std::move(intermediateRelation));
     }
     // Rename them systematically
     renameAtoms(program, outputToIntermediate);
     // Add the rule I <- I'
     for (const auto& outputRelationName : outputRelationNames) {
         auto queryHead = std::make_unique<AstAtom>(outputRelationName);
         auto queryLiteral = std::make_unique<AstAtom>(outputToIntermediate.at(outputRelationName));
         // Give them identical arguments
         const auto* outputRelation = getRelation(program, outputRelationName);
         for (size_t i = 0; i < outputRelation->getArity(); i++) {
             std::stringstream var;
             var << "@query_x" << i;
             queryHead->addArgument(std::make_unique<AstVariable>(var.str()));
             queryLiteral->addArgument(std::make_unique<AstVariable>(var.str()));
         }
         auto query = std::make_unique<AstClause>(std::move(queryHead));
         query->addToBody(std::move(queryLiteral));
         program.addClause(std::move(query));
     }
     return !outputRelationNames.empty();
 }
transform()
bool souffle::NormaliseDatabaseTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
(1) Partition input and output relations
(2) Separate the IDB from the EDB
(3) Normalise arguments within each clause
(4) Querify output relations
Implements souffle::AstTransformer.
Definition at line 178 of file MagicSet.cpp.
References extractIDB(), souffle::AstTranslationUnit::invalidateAnalyses(), normaliseArguments(), partitionIO(), and querifyOutputRelations().
{
     bool changed = false;
     /** (1) Partition input and output relations */
     changed |= partitionIO(translationUnit);
     if (changed) translationUnit.invalidateAnalyses();
     /** (2) Separate the IDB from the EDB */
     changed |= extractIDB(translationUnit);
     if (changed) translationUnit.invalidateAnalyses();
     /** (3) Normalise arguments within each clause */
     changed |= normaliseArguments(translationUnit);
     if (changed) translationUnit.invalidateAnalyses();
     /** (4) Querify output relations */
     changed |= querifyOutputRelations(translationUnit);
     if (changed) translationUnit.invalidateAnalyses();
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp