souffle: souffle::RamEmptinessCheck Class Reference
souffle::RamEmptinessCheck Class Reference
Emptiness check for a relation.
#include <EmptinessCheck.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamEmptinessCheck * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get relation.
RamEmptinessCheck (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Relation.
Detailed Description
Emptiness check for a relation.
Evaluates to true if the given relation is the empty set
For example:
(B = ∅)
Definition at line 45 of file EmptinessCheck.h.
Constructor & Destructor Documentation
RamEmptinessCheck()
souffle::RamEmptinessCheck::RamEmptinessCheck (std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 47 of file EmptinessCheck.h.
References relationRef.
Referenced by clone().
                                                                   : relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "Relation reference is a nullptr");
     }
Member Function Documentation
apply()
void souffle::RamEmptinessCheck::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 64 of file EmptinessCheck.h.
References souffle::map(), and relationRef.
{
         relationRef = map(std::move(relationRef));
     }
clone()
RamEmptinessCheck* souffle::RamEmptinessCheck::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamCondition.
Definition at line 60 of file EmptinessCheck.h.
References souffle::clone(), RamEmptinessCheck(), and relationRef.
Referenced by souffle::test::TEST().
{
         return new RamEmptinessCheck(souffle::clone(relationRef));
     }
equal()
bool souffle::RamEmptinessCheck::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 73 of file EmptinessCheck.h.
References souffle::equal_ptr(), and relationRef.
{
         const auto& other = static_cast<const RamEmptinessCheck&>(node);
         return equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamEmptinessCheck::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 56 of file EmptinessCheck.h.
References relationRef.
{
         return {relationRef.get()};
     }
getRelation()
const RamRelation& souffle::RamEmptinessCheck::getRelation () const inline
Get relation.
Definition at line 52 of file EmptinessCheck.h.
References relationRef.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamComplexityAnalysis::getComplexity(), print(), and souffle::NodeGenerator::visitEmptinessCheck().
{
         return *relationRef->get();
     }
print()
void souffle::RamEmptinessCheck::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 69 of file EmptinessCheck.h.
References souffle::RamRelation::getName(), and getRelation().
{
         os << "(" << getRelation().getName() << " = ∅)";
     }
Field Documentation
relationRef
std::unique_ptr<RamRelationReference> souffle::RamEmptinessCheck::relationRef protected
Relation.
Definition at line 79 of file EmptinessCheck.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRelation(), and RamEmptinessCheck().
The documentation for this class was generated from the following file:
ram/EmptinessCheck.h